# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Bernd Groh <bgroh@redhat.com>, 2003.
# Gerd Koenig <koenig.ulm@googlemail.com>, 2012.
# Miroslav Suchý <msuchy@redhat.com>, 2011.
# sknirT omiT <moc.tahder@sknirtt>, 2010.
# Timo Trinks <ttrinks@redhat.com>, 2006.
# Verena <vfuehrer@redhat.com>, 2004-2005.
# Jiri Dostal <jdostal@redhat.com>, 2018. #zanata
msgid ""
msgstr ""
"Project-Id-Version: Spacewalk\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-04-11 13:25+0200\n"
"PO-Revision-Date: 2024-12-07 15:48+0000\n"
"Last-Translator: Ettore Atalan <atalanttore@googlemail.com>\n"
"Language-Team: German <https://l10n.opensuse.org/projects/uyuni/backend/de/"
">\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Generator: Weblate 5.8.4\n"

#: ../server/apacheAuth.py:72
#, python-format
msgid "incomplete proxy authentication token: %s"
msgstr "unvollständige Kennung zur Proxyauthentisierung: %s"

#: ../server/apacheAuth.py:103
#, python-format
msgid "Sent proxy signature %s does not match ours %s."
msgstr "die gesendete Proxysignatur %s stimmt mit unserer (%s) nicht überein"

#: ../server/apacheAuth.py:142
msgid "declined proxy authentication"
msgstr "abgewiesene Proxyauthentisierung"

#: ../server/apacheRequest.py:67
#, python-format
msgid "Invalid request received (%s)."
msgstr "Ungültige Anfrage erhalten (%s)."

#. Send the message as a fault.
#: ../server/apacheRequest.py:126
#, python-format
msgid ""
"IMPORTANT MESSAGE FOLLOWS:\n"
"%s"
msgstr ""
"NACHFOLGEND EINE WICHTIGE NACHRICHT:\n"
"%s"

#: ../server/apacheRequest.py:156
#, python-format
msgid ""
"While running '%s': caught\n"
"%s : %s\n"
msgstr ""

#. pylint: disable-next=consider-using-f-string
#: ../server/apacheRequest.py:671
#, python-format
msgid "Invalid URI %s"
msgstr "Ungültige URI %s"

#: ../server/handlers/app/packages.py:220
#, python-format
msgid ""
"\n"
"                   %s Account has been deactivated on this server.\n"
"                   Please contact your Org administrator for more help."
msgstr ""
"\n"
"                   %s Benutzer wurde auf diesem Server deaktiviert.\n"
"                   Bitte kontaktieren Sie Ihren Org-Administrator für Hilfe."

#: ../server/handlers/xmlrpc/proxy.py:71
#, fuzzy, python-format
#| msgid "SUSE Manager Proxy service not enabled for server profile: \"%s\""
msgid ""
"SUSE Multi-Linux Manager Proxy service not enabled for server profile: \"%s\""
msgstr ""
"SUSE Manager Proxy Dienst ist nicht für das Server-Profil \"%s\" aktiviert"

#: ../server/handlers/xmlrpc/proxy.py:94
msgid "Invalid session key"
msgstr "Ungültiger Sitzungsschlüssel"

#: ../server/handlers/xmlrpc/proxy.py:102
msgid "This server ID no longer exists"
msgstr "Diese Server-ID existiert nicht mehr"

#: ../server/importlib/userAuth.py:109
msgid "You are not authorized to manage packages in the null org"
msgstr "Sie haben keine Berechtigungen, Pakete in der Null-Org zu verwalten"

#: ../server/importlib/userAuth.py:115
#, python-format
msgid "You are not allowed to manage packages in the %s org"
msgstr "Sie dürfen keine Pakete in der %s-Org verwalten"

#. ok, you're a regular user who doesn't manage any channels.
#. take a hike.
#: ../server/importlib/userAuth.py:132
msgid "You are not allowed to perform administrative tasks"
msgstr "Sie dürfen keine administrativen Aufgaben durchführen"

#: ../server/importlib/userAuth.py:159
#, python-format
msgid ""
"You are not allowed to manage channel %s, or that channel does not exist"
msgstr ""
"Sie dürfen Channel %s nicht verwalten, oder dieser Channel existiert nicht"

#: ../server/importlib/userAuth.py:229
#, fuzzy, python-format
msgid ""
"\n"
"               %s Account has been deactivated on this server.\n"
"               Please contact your Org administrator for more help."
msgstr ""
"\n"
"               %s Benutzer wurde auf diesem Server deaktiviert.\n"
"                   Bitte kontaktieren Sie Ihren Org-Administrator für Hilfe."

#: ../server/rhnChannel.py:2217
#, python-format
msgid ""
"Your account does not have access to any channels matching "
"(release='%(release)s', arch='%(arch)s')%(www_activation)s"
msgstr ""

#: ../server/rhnChannel.py:2236
#, python-format
msgid "Insufficient subscription permissions for release (%s, %s"
msgstr "Ungenügende Berechtigung für Release (%s, %s"

#. Various messages that can be reused
#.
#. bretm 02/07/2007 -- when we have better old-client documentation, probably
#. will be safe to get rid of all this crap
#: ../server/rhnChannel.py:2550 ../server/rhnChannel.py:2569
msgid "System Registered but Inactive"
msgstr "System registriert, aber inaktiv"

#: ../server/rhnChannel.py:2552
#, python-format
msgid ""
"\n"
"Invalid Architecture and OS release combination (%s, %s).\n"
"Your system has been registered, but will not receive updates\n"
"because it could not be subscribed to a base channel.\n"
"Please contact your organization administrator for assistance.\n"
msgstr ""
"\n"
"Ungültige Kombination aus Architektur und Betriebssystemversion (%s, %s).\n"
"Ihr System wurde registriert, wird aber keine Updates erhalten da es keinen\n"
"Basis-Channel abonnieren konnte.\n"
"Bitte kontaktieren Sie zwecks Unterstützung den Org-Administrator.\n"

#: ../server/rhnChannel.py:2561
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but is not yet entitled\n"
"  to service.  To entitle this system to service, login to the web site at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""

#: ../server/rhnChannel.py:2571
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but no service entitlements\n"
"  were available.  To entitle this system to service, login to the web site "
"at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""

#. Invalid server certificate.
#: ../server/rhnHandler.py:62
msgid "Please run rhn_register as root on this client"
msgstr "Bitte führen Sie rhn_register als root auf diesem Client aus"

#: ../server/rhnHandler.py:76
#, python-format
msgid "Service not enabled for system profile: \"%s\""
msgstr "Der Dienst ist für das Systemprofil: \"%s\" nicht aktiviert"

#: ../server/rhnPackage.py:52 ../server/rhnPackage.py:98
#: ../server/rhnPackage.py:118 ../server/rhnPackage.py:179
#, python-format
msgid "Invalid RPM package %s requested"
msgstr "ungültiges rpm Paket %s angefordert"

#: ../server/rhnPackage.py:124
msgid "Package not found"
msgstr "Paket nicht gefunden"

#: ../server/rhnServer/server_class.py:103
#, python-format
msgid "Architecture `%s' is not supported"
msgstr "die Architektur '%s' wird nicht unterstützt"

#: ../server/rhnServer/server_token.py:86
#, python-format
msgid "Token `%s' has more than one base channel assigned"
msgstr "Kennung '%s' hat mehr als einen zugewiesenen Channel"

#: ../server/rhnServer/server_token.py:89
msgid "Conflicting base channels"
msgstr "Konflikt zwischen Basis-Channels"

#: ../server/rhnServer/server_token.py:223
#, python-format
msgid "Failed to add server to group %s"
msgstr "Fehler beim Hinzufügen des Servers zur Gruppe %s"

#: ../server/rhnServer/server_token.py:574
#, python-format
msgid "Maximum usage count of %s reached"
msgstr "Maximale Nutzung von %s erreicht"

#: ../server/rhnServer/server_token.py:869
msgid ""
"Stacking of re-registration tokens with different base entitlements is not "
"supported"
msgstr ""

#: ../server/rhnServer/server_token.py:946
#, python-format
msgid "Could not find token '%s'"
msgstr "Konnte Token '%s' nicht finden"

#. Cannot use activation keys from different orgs
#: ../server/rhnServer/server_token.py:979
msgid "Tokens from mismatching orgs"
msgstr "Tokens von nicht übereinstimmenden Orgs"

#. Two tokens with different kickstart sessions
#: ../server/rhnServer/server_token.py:989
msgid "Kickstart session mismatch"
msgstr "Kickstart-Sitzung stimmt nicht überein"

#: ../server/rhnServer/server_token.py:1013
msgid "Stacking of re-registration tokens is not supported"
msgstr ""

#: ../server/rhnUser.py:327 ../server/rhnUser.py:330
msgid "Invalid username/password combination"
msgstr "Ungültige Kombination von Benutzername und Passwort"

#. nope, not reserved either
#: ../server/rhnUser.py:527
#, python-format
msgid "Username `%s' has not been reserved"
msgstr "der Benutzername '%s' wurde nicht reserviert"

#. New accounts have to specify an e-mail address
#: ../server/rhnUser.py:533
msgid "E-mail address not specified"
msgstr "die Emailadresse wurde nicht angegeben"

#: ../server/rhnUser.py:575
#, python-format
msgid "username should be at least %d characters"
msgstr "der Benutzername muss mindestens %d Zeichen lang sein"

#: ../server/rhnUser.py:579
#, python-format
msgid "username should be less than %d characters"
msgstr "der Benutzername darf höchstens %d Zeichen lang sein"

#: ../server/rhnUser.py:593
#, python-format
msgid "username = `%s', invalid character `%s'"
msgstr "Benutzername = '%s', ungültiges Zeichen '%s'"

#: ../server/rhnUser.py:614
#, python-format
msgid "Please limit your e-mail address to %s chars"
msgstr "Bitte beschränken Sie Ihre Emailadresse auf %s Zeichen"

#: ../server/rhnUser.py:704
#, python-format
msgid "password must be at least %d characters"
msgstr "das Passwort muss mindestens %d Zeichen lang sein"

#: ../server/rhnUser.py:708
#, python-format
msgid "Password must be shorter than %d characters"
msgstr "Das Passwort darf höchstens %d Zeichen lang sein"

#: ../server/rhnUser.py:724
#, python-format
msgid "password contains character `%s'"
msgstr "das Passwort enthält das Zeichen `%s'"

#: ../server/rhnUser.py:733
#, python-format
msgid "username should be at least %d characters long"
msgstr "der Benutzername muss mindestens %d Zeichen lang sein"

#: ../server/rhnUser.py:744
#, python-format
msgid "Cannot register usernames ending with %s"
msgstr "Benutzernamen, die auf %s enden können nicht registriert werden"

#. 0-999: Red Hat client/client-like interaction errors:
#: ../common/rhnException.py:55
msgid "This does not appear to be a valid username."
msgstr "Dies scheint kein gültiger Benutzername zu sein."

#: ../common/rhnException.py:56
msgid "Invalid username and password combination."
msgstr "Ungültige Kombination von Benutzername und Passwort"

#: ../common/rhnException.py:57
msgid "This login is already taken, or the password is incorrect."
msgstr "Dieses Login wird bereits verwendet oder das Passwort ist falsch."

#: ../common/rhnException.py:58
msgid "Permission denied."
msgstr "Zugriff verweigert."

#: ../common/rhnException.py:59
msgid "Object not found."
msgstr "Objekt nicht gefunden."

#: ../common/rhnException.py:60
msgid "Invalid System Digital ID."
msgstr "Ungültige System Digital-ID."

#: ../common/rhnException.py:61
msgid "Invalid System Credentials."
msgstr "Ungültige System-Berechtigungsnachweise."

#: ../common/rhnException.py:62
msgid "Could not retrieve user data from database."
msgstr "Benutzerdaten konnten nicht von Datenbank abrufen werden."

#: ../common/rhnException.py:63
msgid "Valid username required."
msgstr "Gültiger Benutzername erforderlich."

#: ../common/rhnException.py:64
msgid "Valid password required."
msgstr "Gültiges Passwort erforderlich."

#: ../common/rhnException.py:65
msgid "Minimum username length violation."
msgstr "Minimallänge des Benutzernamen nicht erfüllt."

#: ../common/rhnException.py:66
msgid "Minimum password length violation."
msgstr "Minimallänge des Passworts nicht erfüllt."

#: ../common/rhnException.py:67
msgid "The username contains invalid characters."
msgstr "Der Benutzername enthält ungültige Zeichen."

#: ../common/rhnException.py:68
msgid "File not found."
msgstr "Datei nicht gefunden."

#: ../common/rhnException.py:69
msgid "Architecture and OS version combination is not supported."
msgstr ""
"Diese Kombination aus Architektur und OS Version wird nicht unterstützt."

#: ../common/rhnException.py:70
msgid "Could not retrieve system data from database."
msgstr "Systemdaten konnten in der Datenbank nicht gefunden werden."

#: ../common/rhnException.py:71
msgid "Invalid arguments passed to function."
msgstr "Der Funktion wurden ungültige Werte übergeben."

#: ../common/rhnException.py:72
msgid "Unable to retrieve requested entry."
msgstr "Eintrag konnte nicht abgerufen werden."

#: ../common/rhnException.py:73
msgid "Could not update database entry."
msgstr "Datenbankeintrag konnte nicht aktualisiert werden."

#: ../common/rhnException.py:74
msgid "Unsupported server architecture."
msgstr "Serverarchitektur wird nicht unterstützt."

#: ../common/rhnException.py:76
#, python-format
msgid ""
"\n"
"     The anonymous server functionality is no longer available.\n"
"\n"
"     Please re-register this system by running mgr_register as root.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable the service for this "
"system.\n"
"     "
msgstr ""

#: ../common/rhnException.py:85
msgid "Record not available in the database."
msgstr "Kein Eintrag in der Datenbank."

#: ../common/rhnException.py:86
msgid "Invalid value for entry."
msgstr "Ungültiger Wert."

#: ../common/rhnException.py:88
#, python-format
msgid ""
"\n"
"     This system does not have a valid entitlement for SUSE Multi-Linux "
"Manager.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable the service for this "
"system.\n"
"     "
msgstr ""

#: ../common/rhnException.py:95
msgid "Channel error"
msgstr "Channel Fehler"

#: ../common/rhnException.py:96
msgid "Client session token is invalid."
msgstr "Client Session Token ist ungültig."

#: ../common/rhnException.py:97
msgid "Client session token has expired."
msgstr "Client Session ist abgelaufen."

#: ../common/rhnException.py:98
msgid "You are not authorized to retrieve the requested object."
msgstr "Sie sind nicht berechtigt dieses Objekt abzurufen."

#: ../common/rhnException.py:99
msgid "Invalid action"
msgstr "Ungültige Aktion"

#: ../common/rhnException.py:101
msgid "You are not allowed to perform administrative tasks on this system."
msgstr "Sie sind für Administative Tätigkeiten nicht freigegeben."

#: ../common/rhnException.py:104
msgid "The system is already subscribed to the specified channel."
msgstr "Dieses System ist bereits bei diesem Channel registriert."

#: ../common/rhnException.py:105
msgid "The system is not currently subscribed to the specified channel."
msgstr "Dieses System ist bei diesem Channel nicht registriert."

#: ../common/rhnException.py:106
msgid "The specified channel does not exist."
msgstr "Der angegebene Channel existiert nicht."

#: ../common/rhnException.py:107
msgid "Invalid channel version."
msgstr "Ungültige Channel-Version."

#: ../common/rhnException.py:109
msgid ""
"\n"
"     User group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     user account. Please check with the organization administrator for "
"your\n"
"     account if the maximum number of users allowed to subscribe to server "
"needs\n"
"     to be changed.\n"
"     "
msgstr ""

#: ../common/rhnException.py:119
msgid ""
"\n"
"     System group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     system profile. Please check with the organization administrator for "
"your\n"
"     account for modifying the maximum number of system profiles that can "
"be\n"
"     subscribed to your account.\n"
"     "
msgstr ""

#: ../common/rhnException.py:129
#, fuzzy
msgid ""
"\n"
"     Invalid architecture.\n"
"\n"
"     The architecture of the package is not supported by\n"
"     "
msgstr ""
"\n"
"     Ungültige Architektur.\n"
"\n"
"     Die Architektur dieses Paketes ist vom Red Hat Network nicht "
"unterstützt\n"
"     "

#: ../common/rhnException.py:136
msgid "Invalid RPM header"
msgstr "Ungültiger RPM Header"

#: ../common/rhnException.py:138
msgid ""
"\n"
"    This system is already registered as a Salt Minion. If you want to "
"register it as a traditional client\n"
"    please delete it first via the web UI or API and then register it using "
"the traditional tools.\n"
"    "
msgstr ""

#. For the uploading tools
#: ../common/rhnException.py:144
msgid "Invalid information uploaded to the server"
msgstr "Es wurden ungültige Informationen hochgeladen"

#: ../common/rhnException.py:145
msgid "Error uploading network interfaces configuration."
msgstr "Fehler beim Hochladen der Konfiguration der Netzwerk-Schnittstellen."

#: ../common/rhnException.py:147
msgid ""
"\n"
"     Package Upload Failed due to uniqueness constraint violation.\n"
"     Make sure the package does not have any duplicate dependencies or\n"
"     does not already exists on the server\n"
"     "
msgstr ""
"\n"
"     Hochladen des Paketes fehlgeschlagen. \n"
"     Bitte prüfen Sie ob das Paket keine doppelten Abhängigkeiten besitzt\n"
"      und nicht schon bereits auf dem Server vorhanden ist\n"
"     "

#: ../common/rhnException.py:154
#, fuzzy
#| msgid ""
#| "\n"
#| "     The --force mgrpush option is disabled on this server.\n"
#| "     Please contact your SUSE Manager administrator for more help.\n"
#| "     "
msgid ""
"\n"
"     The --force mgrpush option is disabled on this server.\n"
"     Please contact your SUSE Multi-Linux Manager administrator for more "
"help.\n"
"     "
msgstr ""
"\n"
"     Die Option --force mgrpush wurde auf diesem Server deaktiviert. \n"
"     Bitte kontaktieren Sie Ihren SUSE-Administrator für Hilfestellung.\n"
"     "

#: ../common/rhnException.py:161
msgid ""
"\n"
"     The activation token specified could not be found on the server.\n"
"     Please retry with a valid key.\n"
"     "
msgstr ""
"\n"
"     Das Aktivierungstoken konnte nicht auf diesem Server gefunden werden. \n"
"\tBitte versuchen Sie es mit einem gültigen Schlüssel erneut.\n"
"     "

#: ../common/rhnException.py:166
msgid "Too many systems registered using this registration token"
msgstr "Zuviele Systeme sind dieser Registration zugeordnet"

#: ../common/rhnException.py:167
msgid "Token contains invalid, obsoleted or insufficient settings"
msgstr ""
"Dieser Token enthält ungültige, obsolete oder nicht ausreichende "
"Einstellungen"

#: ../common/rhnException.py:168
msgid "Conflicting activation tokens"
msgstr "Aktivierungs-Tokens mit Konflikten"

#: ../common/rhnException.py:171
msgid ""
"\n"
"     No matching base channel found for your system.\n"
"     "
msgstr ""

#: ../common/rhnException.py:176
msgid ""
"\n"
"     You do not have subscription permission to the designated channel.\n"
"     Please refer to your organization's channel or organization\n"
"     administrators for further details.\n"
"     "
msgstr ""

#: ../common/rhnException.py:182
msgid "You can not unsubscribe from base channel."
msgstr "Sie können sich von diesem Base-Channel nicht abmelden."

#: ../common/rhnException.py:183
msgid "SUSE Multi-Linux Manager or Proxy channel can not be subscribed."
msgstr ""

#. 80-90: server group errors
#: ../common/rhnException.py:185
msgid "There was an error while trying to join the system to its groups"
msgstr "Fehler beim Hinzufügen des Systems in die entsprechenden Gruppen"

#. 90-100: entitlement errors
#: ../common/rhnException.py:187
msgid "Unable to entitle system"
msgstr "System kann nicht berechtigt werden"

#. 100-109: e-mail and uuid related faults
#: ../common/rhnException.py:189
msgid "Maximum e-mail length violation."
msgstr "Maximale Länge der Email überschritten."

#: ../common/rhnException.py:190
msgid "This system has been previously registered."
msgstr "Dieses System wurde bereits registriert."

#: ../common/rhnException.py:191
msgid "Invalid username"
msgstr "Benutzername ungültig"

#. 140-159 applet errors
#: ../common/rhnException.py:193
msgid "Unable to look up server"
msgstr ""

#. 160-179: OSAD errors
#: ../common/rhnException.py:195
msgid "Required argument is missing"
msgstr "Benötigte Angabe fehlt"

#. 600-699: RHEL5+ EN errors
#: ../common/rhnException.py:197
msgid "No entitlement information tied to hardware"
msgstr ""

#: ../common/rhnException.py:198
msgid "Installation number is not entitling"
msgstr ""

#. 700-799: Additional user input verification errors.
#: ../common/rhnException.py:200
msgid "Maximum username length violation"
msgstr "Maximale Länge des Benutzernamen überschritten"

#: ../common/rhnException.py:201
msgid "Maximum password length violation"
msgstr "Maximale Passwortlänge überschritten"

#: ../common/rhnException.py:202
msgid "This user has read only API access. Action denied."
msgstr ""

#: ../common/rhnException.py:203
#, fuzzy
msgid "System Name cannot be less than 1 character"
msgstr "der Benutzername darf höchstens %d Zeichen lang sein"

#. 1000-1999: Proxy specific errors:
#. issued by a Proxy to the client
#: ../common/rhnException.py:206
#, fuzzy
msgid "SUSE Multi-Linux Manager Proxy error."
msgstr "RHN Proxy Fehler."

#: ../common/rhnException.py:207
#, fuzzy
msgid "SUSE Multi-Linux Manager Proxy unable to login."
msgstr "Login zum RHN Proxy nicht möglich."

#: ../common/rhnException.py:210
msgid ""
"\n"
"     SUSE Multi-Linux Manager Proxy system ID does not match a Spacewalk "
"Proxy Server\n"
"     in the database.\n"
"     "
msgstr ""

#: ../common/rhnException.py:215
#, fuzzy
msgid "SUSE Multi-Linux Manager Proxy session token is invalid."
msgstr "RHN Proxy Session-Token ist ungültig."

#: ../common/rhnException.py:216
#, fuzzy
msgid "SUSE Multi-Linux Manager Proxy session token has expired."
msgstr "RHN Proxy Session Token abgelaufen."

#: ../common/rhnException.py:220
msgid ""
"\n"
"      user creation is not allowed via mgr_register;\n"
"     please contact your sysadmin to have your account created.\n"
"     "
msgstr ""

#: ../common/rhnException.py:226
#, fuzzy
msgid ""
"\n"
"     This SUSE Multi-Linux Manager server is not allowed to use Inter Server "
"Sync on this server\n"
"     "
msgstr ""
"\n"
"     Diesem Satellite Server fehlt die Berechtigung für Inter Satellite Sync "
"auf diesem Satellite\n"
"     "

#: ../common/rhnException.py:231
#, fuzzy
msgid ""
"\n"
"     Inter Server Sync is disabled on this SUSE Multi-Linux Manager Server.\n"
"     "
msgstr ""
"\n"
"     Inter Satellite Sync ist auf diesem Satellite deaktiviert.\n"
"     "

#. 3000-3999: XML dumper errors:
#: ../common/rhnException.py:236
msgid "Invalid datatype passed"
msgstr "Es wurde ein ungültiger Datentyp übergeben"

#: ../common/rhnException.py:237
msgid "Unable to retrieve channel"
msgstr "Channels konnten nicht abgerufen werden"

#: ../common/rhnException.py:238
msgid "Unable to retrieve package"
msgstr "Pakete konnten nicht abgerufen werden"

#: ../common/rhnException.py:239
msgid "Unable to retrieve erratum"
msgstr "Erratum konnte nicht abgerufen werden"

#: ../common/rhnException.py:240
msgid "File is missing"
msgstr "Datei nicht vorhanden"

#: ../common/rhnException.py:241
msgid "Function retrieval error"
msgstr ""

#: ../common/rhnException.py:242
msgid "Function execution error"
msgstr ""

#: ../common/rhnException.py:243
msgid "Missing version string"
msgstr "Es wurde keine Version angegeben"

#: ../common/rhnException.py:244
msgid "Invalid version string"
msgstr "Ungültige Version"

#: ../common/rhnException.py:245
msgid "Mismatching versions"
msgstr "Versionen stimmen nicht überein"

#: ../common/rhnException.py:246
msgid "Invalid channel version"
msgstr "Ungültige Channel-Version"

#: ../common/rhnException.py:247
msgid "No comps file for channel"
msgstr "Keine Chomps-Datei für dem Channel"

#: ../common/rhnException.py:248
msgid "Unable to retrieve comps file"
msgstr "Comps-Datei kann nicht abgerufen werden."

#. 4000 - 4999: config management errors
#: ../common/rhnException.py:250
msgid "Configuration action missing"
msgstr ""

#: ../common/rhnException.py:251
msgid "File too large"
msgstr "Datei zu gross"

#: ../common/rhnException.py:252
msgid "File contains binary data"
msgstr "Datei enthält binäre Daten"

#: ../common/rhnException.py:253
msgid "Configuration channel is not empty"
msgstr "Konfigurations-Channel enthält Daten"

#: ../common/rhnException.py:254
msgid "Permission error"
msgstr "Zugriff nicht erlaubt"

#: ../common/rhnException.py:255
msgid "Content missing for configuration file"
msgstr "Kein Inhalt für Konfigurationsdatei"

#: ../common/rhnException.py:256
msgid "Template delimiters not specified"
msgstr "Die Template Trennzeichen sind nicht spezifiziert"

#: ../common/rhnException.py:257
msgid "Configuration channel does not exist"
msgstr "Konfigurations-Channel existiert nicht"

#: ../common/rhnException.py:258
msgid "Configuration channel already exists"
msgstr "Konfigrations-Channel bereits vorhanden"

#: ../common/rhnException.py:259
msgid "File missing from configuration channel"
msgstr "Die Datei aus dem Konfigurationskanal fehlt"

#: ../common/rhnException.py:260
msgid "Different revision of this file is uploaded"
msgstr "Eine andere Version dieser Datei wurde breits hochgeladen"

#: ../common/rhnException.py:261
msgid "File already uploaded to configuration channel"
msgstr "Datei wurde breits in den Konfigations-Channel hochgeladen"

#: ../common/rhnException.py:262
msgid "File size exceeds remaining quota space"
msgstr "Die Dateigröße überschreitet die verbleibende Quota (Speicherplatz)"

#: ../common/rhnException.py:263
msgid "Full path of file must be specified"
msgstr "Der vollständige Datei-Pfad muss angegeben werden"

#: ../common/rhnException.py:264
msgid "Invalid revision number"
msgstr "Ungültige Revisionsnummer"

#: ../common/rhnException.py:265
msgid "Cannot compare files of different file type"
msgstr ""
"Ein Vergeich zwischen verschiedenen Datei-Typen kann nicht erstellt werden"

#. 5100 - 5199: scap results reporting error
#: ../common/rhnException.py:267
msgid "SCAP results file transfer is invalid or incomplete"
msgstr ""

#: ../common/rhnException.py:268
msgid "Error composing directory path for detailed SCAP results"
msgstr ""

#: ../common/rhnException.py:269
msgid "Error composing file path for detailed SCAP results"
msgstr ""

#: ../common/rhnException.py:270
#, fuzzy
msgid "Invalid content encoding"
msgstr "Ungültiger Feldcode"

#: ../common/rhnException.py:317
#, fuzzy
msgid ""
"\n"
"     An error has occurred while processing your request. If this problem\n"
"     persists please enter a bug report at scc.suse.com.\n"
"     If you choose to submit the bug report, please be sure to include\n"
"     details of what you were trying to do when this error occurred and\n"
"     details on how to reproduce this problem.\n"
msgstr ""
"\n"
"     Bei der Bearbeitung Ihrer Anfrage trat ein Fehler auf. Falls dieses "
"Problem\n"
"     weiterhin auftritt, reichen Sie bitte einen Fehlerbericht unter "
"bugzilla.redhat.com ein.\n"
"     Falls Sie sich dazu entschließen, einen Fehlerbericht einzureichen, "
"stellen Sie bitte sicher,\n"
"     dass Sie Details zu den von Ihnen durchgeführten Schritten liefern, als "
"dieser Fehler auftrat,\n"
"     sowie Informationen, wie dieses Problem reproduziert werden kann.\n"

#: ../common/rhnException.py:368
#, python-format
msgid ""
"Error Message:\n"
"    %s\n"
msgstr ""
"Fehlermeldung:\n"
"    %s\n"

#: ../common/rhnException.py:370
#, python-format
msgid "Error Class Code: %s\n"
msgstr "Fehlerklasse-Code: %s\n"

#: ../common/rhnException.py:373
#, python-format
msgid "Error Class Info: %s\n"
msgstr "Fehlerklasse-Information: %s\n"

#: ../common/rhnException.py:375
#, python-format
msgid "Explanation: %s"
msgstr "Erklärung: %s"

#: ../common/rhnTB.py:220
#, python-format
msgid "ERROR: %s %s: %s"
msgstr ""

#: ../common/rhnTB.py:221
#, python-format
msgid "TRACEBACK: %s"
msgstr ""

#: ../satellite_tools/disk_dumper/iss.py:1634
#: ../satellite_tools/disk_dumper/iss.py:1640
#, python-format
msgid "format of %s should be at least YYYYMMDD.\n"
msgstr ""

#: ../satellite_tools/messages.py:28
#, python-format
msgid ""
"\n"
"ERROR: executing step %s. Error is:\n"
"%s\n"
msgstr ""

#: ../satellite_tools/messages.py:35
#, python-format
msgid ""
"\n"
"ERROR: there was a problem accessing the channel data from your temporary\n"
"       repository. Did you migrate all of the data from the channel ISOs\n"
"       do this directory? If so, please recheck the channels ISOs, ensure\n"
"       that you have them all, and then iteratively remount and repopulate\n"
"       the temporary repository (%s).\n"
msgstr ""

#: ../satellite_tools/messages.py:45
#, python-format
msgid ""
"\n"
"ERROR: there was a problem synchronizing the information.\n"
"       Error message: %s\n"
msgstr ""

#: ../satellite_tools/messages.py:52
#, python-format
msgid ""
"\n"
"ERROR: There was a problem communicating with the ISS Master.\n"
"       Depending on the specific error details, please review your "
"configuration,\n"
"       basic network connectivity, and/or name resolution, and try again.\n"
"       Error message: %s\n"
msgstr ""

#: ../satellite_tools/messages.py:61
#, python-format
msgid ""
"\n"
"ERROR: a child-channel cannot be synced without its parent being synced as\n"
"       well. A parent needs to be either (a) previously synced or (b) "
"synced\n"
"       in tandem with the desired child-channel. Missing parents for this\n"
"       transaction:\n"
"       %s\n"
msgstr ""

#: ../satellite_tools/messages.py:71
#, python-format
msgid ""
"\n"
"ERROR: you are not entitled to sync a channel in this set of channels.\n"
"Please contact your SUSE Multi-Linux Manager contact\n"
"%s"
msgstr ""

#: ../satellite_tools/messages.py:77
#, python-format
msgid "  ERROR: not enough free space (%s KB) on device."
msgstr ""

#: ../satellite_tools/messages.py:79
#, python-format
msgid "    %3d/%s Fetch successful: %s (%s bytes)"
msgstr ""

#: ../satellite_tools/messages.py:80
#, fuzzy, python-format
msgid "    Extinct package:  %s"
msgstr "Paket erwartet, nicht: %s"

#: ../satellite_tools/messages.py:81
#, python-format
msgid "   Total size: %s"
msgstr ""

#: ../satellite_tools/messages.py:83
#, python-format
msgid "      Downloaded %s of %s. Estimated remaining time: %s"
msgstr ""

#: ../satellite_tools/messages.py:85
#, python-format
msgid "    Fetch unsuccessful: %s"
msgstr ""

#: ../satellite_tools/messages.py:86
#, python-format
msgid "   RPM fetch summary: %s"
msgstr ""

#: ../satellite_tools/messages.py:87
#, python-format
msgid "       success: %d"
msgstr ""

#: ../satellite_tools/messages.py:88
#, python-format
msgid "       failed:  %d"
msgstr ""

#: ../satellite_tools/messages.py:89
#, python-format
msgid "       extinct: %d"
msgstr ""

#: ../satellite_tools/messages.py:91
#, python-format
msgid "   Retrieving / parsing *relevant* package metadata: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:92
#, python-format
msgid "   Retrieving / parsing errata data: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:93
#, python-format
msgid "   Retrieving / parsing kickstart data: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:94
#, python-format
msgid "   Retrieving / parsing kickstart tree files: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:95
#, python-format
msgid "   Importing *relevant* package metadata: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:96
msgid "   * WARNING: this may be a slow process."
msgstr ""

#: ../satellite_tools/messages.py:97
#, fuzzy
msgid "Linking packages to channels"
msgstr "Konflikt zwischen Basis-Channels"

#: ../satellite_tools/messages.py:98
#, python-format
msgid "   Importing *relevant* errata: %s (%s)"
msgstr ""

#: ../satellite_tools/messages.py:99
msgid "   No new kickstartable tree to import"
msgstr ""

#: ../satellite_tools/messages.py:100
#, python-format
msgid "Importing kickstartable trees (%d)"
msgstr ""

#: ../satellite_tools/messages.py:101
#, python-format
msgid "Imported kickstartable trees (%d)"
msgstr ""

#: ../satellite_tools/reposync.py:138
msgid "+++ sending log as an email +++"
msgstr ""

#: ../satellite_tools/reposync.py:141
#, python-format
msgid "%s sync. report from %s"
msgstr ""

#: ../satellite_tools/reposync.py:151
msgid "+++ email requested, but there is nothing to send +++"
msgstr ""

#~ msgid "ISS is disabled on this server."
#~ msgstr "ISS ist auf diesem Server deaktiviert."

#, python-format
#~ msgid "Server \"%s\" is not enabled for ISS."
#~ msgstr "Server \"%s\" nicht für ISS aktiviert."

#~ msgid "Retrieving / parsing channel data"
#~ msgstr "Kanaldaten werden abgerufen / geparst"

#~ msgid "Channel data complete"
#~ msgstr "Kanaldaten vollständig"

#, python-format
#~ msgid "%10s import from %s"
#~ msgstr "%10s importieren von %s"

#, python-format
#~ msgid "%10s import from %s - %s"
#~ msgstr "%10s von %s importieren - %s"

#, python-format
#~ msgid "%10s"
#~ msgstr "%10s"

#~ msgid "   p = previously imported/synced channel"
#~ msgstr "   p = zuvor importierter/synchronisierter Kanal"

#~ msgid "   . = channel not yet imported/synced"
#~ msgstr "   . = Kanal noch nicht importiert/synchronisiert"

#~ msgid "   e = channel no longer supported (end-of-service)"
#~ msgstr "   e = Kanal wird nicht mehr unterstützt (Dienstende)"

#, python-format
#~ msgid "   %s:"
#~ msgstr "   %s:"

#, python-format
#~ msgid "      %s %-40s %4s %s"
#~ msgstr "      %s %-40s %4s %s"

#~ msgid "base-channels"
#~ msgstr "Basiskanäle"

#~ msgid "NONE RELEVANT"
#~ msgstr "NICHT RELEVANT"

#~ msgid "end-of-service"
#~ msgstr "Dienstende"

#~ msgid "   typos:"
#~ msgstr "   Tippfehler:"

#, python-format
#~ msgid "XXX: imported channels: %s"
#~ msgstr "XXX: importierte Kanäle: %s"

#~ msgid "ERROR: these channels either do not exist or are not available:"
#~ msgstr ""
#~ "FEHLER: diese Kanäle existieren entweder nicht oder sind nicht verfügbar:"

#~ msgid "Downloading rpm packages"
#~ msgstr "rpm-Pakete werden heruntergeladen"

#~ msgid "NONE MISSING"
#~ msgstr "KEINE FEHLEN"

#~ msgid "Downloading package metadata"
#~ msgstr "Paketmetadaten werden heruntergeladen"

#~ msgid "Downloading srpm packages"
#~ msgstr "srpm-Pakete werden heruntergeladen"

#~ msgid "Downloading source package metadata"
#~ msgstr "Quellpaketmetadaten werden heruntergeladen"

#, python-format
#~ msgid "Unable to save file %s: %s"
#~ msgstr "Datei %s konnte nicht gespeichert werden: %s"

#, python-format
#~ msgid "Failed to fetch file %s"
#~ msgstr "Datei %s konnte nicht abgerufen werden"

#~ msgid "Downloading patch data"
#~ msgstr "Patchdaten werden heruntergeladen"

#~ msgid "Downloading:"
#~ msgstr "Herunterladen:"

#~ msgid " - complete"
#~ msgstr " - abgeschlossen"

#~ msgid "Importing source package metadata"
#~ msgstr "Quellpaketmetadaten werden importiert"

#~ msgid "Importing package metadata"
#~ msgstr "Paketmetadaten werden importiert"

#, fuzzy
#~ msgid "print the configuration and exit"
#~ msgstr "Konfigurations-Channel existiert nicht"

#, fuzzy
#~ msgid "  12 - Channel do not exist"
#~ msgstr "Der angegebene Channel existiert nicht."

#~ msgid "  25 - no such directory"
#~ msgstr "  25 - kein solches Verzeichnis"

#~ msgid "  26 - mount_point does not exist"
#~ msgstr "  26 - Einhängepunkt existiert nicht"

#, python-brace-format
#~ msgid "Your system was not found in the {PRODUCT_NAME} database"
#~ msgstr "Ihr System wurde in der {PRODUCT_NAME} Datenbank nicht gefunden"

#, python-format
#~ msgid "Expected a package name, not: %s"
#~ msgstr "Paketname erwartet, nicht: %s"

#, python-format
#~ msgid "Expected a package, not: %s"
#~ msgstr "Paket erwartet, nicht: %s"

#, python-format
#~ msgid "Invalid action value type %s (%s)"
#~ msgstr "Ungültiger Aktionswerttyp %s (%s)"

#, python-format
#~ msgid "Action %s does not belong to server %s"
#~ msgstr "Aktion %s gehört nicht zu Server %s"

#~ msgid "Required data missing"
#~ msgstr "Erforderliche Daten nicht vorhanden"

#~ msgid "Required members missing"
#~ msgstr "Erforderliche Mitglieder fehlen"

#~ msgid "Attempt to register a system to an invalid username"
#~ msgstr ""
#~ "Versuch, ein System mit einem ungültigen Benutzernamen zu registrieren"

#~ msgid "Invalid system release version requested"
#~ msgstr "Ungültige System-Release-Version angefordert"

#~ msgid ""
#~ "Unable to find a valid network interface, both ipaddr and ip6addr not "
#~ "found."
#~ msgstr ""
#~ "Kein gültiges Netzwerk Interface gefunden. Sowohl ipaddr als auch ip6addr "
#~ "konnten nicht gefunden werden."

#, python-brace-format
#~ msgid "{PRODUCT_NAME} Welcome Message"
#~ msgstr "{PRODUCT_NAME} Willkommensnachricht"

#~ msgid "Privacy Statement"
#~ msgstr "Datenschutzerklärung"

#~ msgid "Expected a dictionary as a product argument"
#~ msgstr "Es wurde ein Wörterbuch als Produktargument erwartet"

#, python-format
#~ msgid "Invalid value '%s' for %s (%s)"
#~ msgstr "Ungültiger Wert '%s' für %s (%s)"

#~ msgid "Invalid system_id/action_id pair."
#~ msgstr "Ungültiges system_id/action_id Paar."

#, python-format
#~ msgid "Invalid value %s (%s)"
#~ msgstr "Ungültiger Wert %s (%s)"

#, fuzzy
#~ msgid "Invalid crash name"
#~ msgstr "Ungültiger Paketname"

#, fuzzy
#~ msgid ""
#~ "\n"
#~ "Invalid Architecture and OS release combination (%s, %s).\n"
#~ "Your system has been registered, but will not receive updates\n"
#~ "because it is not subscribed to a channel. If you have not yet\n"
#~ "activated your product for service, please visit our website at:\n"
#~ "\n"
#~ "     http://www.redhat.com/apps/activate/\n"
#~ "\n"
#~ "...to activate your product."
#~ msgstr ""
#~ "\n"
#~ "Ungültige Kombination aus Architektur und Betriebssystemversion (%s, "
#~ "%s).\n"
#~ "Ihr System wurde registriert, wird aber keine Updates erhalten, da es "
#~ "keinen\n"
#~ "Channel abonniert hat. Falls Sie Ihr System bislang nicht aktiviert "
#~ "haben,\n"
#~ "besuchen Sie bitte unsere Webseite unter:\n"
#~ "  \n"
#~ "     http://www.redhat.com/apps/activate/\n"
#~ "\n"
#~ "...um Ihr Produkt zu aktivieren."

#~ msgid "Your system was not found in the RHN database"
#~ msgstr "Ihr System wurde in der RHN Datenbank nicht gefunden"

#~ msgid "Red Hat Satellite Welcome Message"
#~ msgstr "Red Hat Network Willkommensmitteilung"

#~ msgid "Red Hat Satellite Privacy Statement"
#~ msgstr "SUSE Manager Datenschutzerklärung"
