# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Leah Liu <lliu@redhat.com>, 2010.
# Leah Liu <weliu@redhat.com>, 2005, 2006.
# Sarah Smith <sarahs@redhat.com>, 2002.
# Sarah Wang <sarahs@redhat.com>, 2003, 2004.
# Tony Fu <tfu@redhat.com>, 2004, 2006.
# Xi Huang <xhuang@redhat.com>, 2006.
# Xi HUANG <xhuang@redhat.com>, 2007.
msgid ""
msgstr ""
"Project-Id-Version: Spacewalk\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-08-16 08:38+0000\n"
"PO-Revision-Date: 2020-12-29 08:37+0000\n"
"Last-Translator: Emily Dong <Emily.Dong@excel-gits.com>\n"
"Language-Team: Chinese (China) <https://l10n.opensuse.org/projects/uyuni/"
"backend/zh_CN/>\n"
"Language: zh_CN\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Generator: Weblate 3.6.1\n"

#: ../server/rhnServer/server_class.py:97
#, python-format
msgid "Architecture `%s' is not supported"
msgstr "不支持体系结构 `%s'"

#: ../server/rhnServer/server_token.py:78
#, python-format
msgid "Token `%s' has more than one base channel assigned"
msgstr "为令牌 `%s' 指派了多个基础频道"

#: ../server/rhnServer/server_token.py:80
msgid "Conflicting base channels"
msgstr "有冲突的基础频道"

#: ../server/rhnServer/server_token.py:190
#, python-format
msgid "Failed to add server to group %s"
msgstr "无法将服务器添加到组 %s"

#: ../server/rhnServer/server_token.py:503
#, python-format
msgid "Maximum usage count of %s reached"
msgstr "已达到 %s 的最大用量计数"

#: ../server/rhnServer/server_token.py:744
msgid ""
"Stacking of re-registration tokens with different base entitlements is not "
"supported"
msgstr "不支持将重新注册令牌与不同的基础权利堆叠到一起"

#: ../server/rhnServer/server_token.py:811
#, python-format
msgid "Could not find token '%s'"
msgstr "找不到令牌 '%s'"

#. Cannot use activation keys from different orgs
#: ../server/rhnServer/server_token.py:843
msgid "Tokens from mismatching orgs"
msgstr "来自不匹配的组织的令牌"

#. Two tokens with different kickstart sessions
#: ../server/rhnServer/server_token.py:853
msgid "Kickstart session mismatch"
msgstr "Kickstart 会话不匹配"

#: ../server/rhnServer/server_token.py:877
msgid "Stacking of re-registration tokens is not supported"
msgstr "不支持堆叠重新注册令牌"

#: ../server/rhnUser.py:289 ../server/rhnUser.py:292
msgid "Invalid username/password combination"
msgstr "无效的用户名/口令组合"

#. nope, not reserved either
#: ../server/rhnUser.py:467
#, python-format
msgid "Username `%s' has not been reserved"
msgstr "未保留用户名 `%s'"

#. New accounts have to specify an e-mail address
#: ../server/rhnUser.py:473
msgid "E-mail address not specified"
msgstr "未指定电子邮件地址"

#: ../server/rhnUser.py:509
#, python-format
msgid "username should be at least %d characters"
msgstr "用户名应至少为 %d 个字符"

#: ../server/rhnUser.py:512
#, python-format
msgid "username should be less than %d characters"
msgstr "用户名应小于 %d 个字符"

#: ../server/rhnUser.py:523
#, python-format
msgid "username = `%s', invalid character `%s'"
msgstr "用户名 = `%s'，字符 `%s' 无效"

#: ../server/rhnUser.py:542
#, python-format
msgid "Please limit your e-mail address to %s chars"
msgstr "请将您的电子邮件地址限制为 %s 个字符"

#: ../server/rhnUser.py:623
#, python-format
msgid "password must be at least %d characters"
msgstr "口令必须至少为 %d 个字符"

#: ../server/rhnUser.py:626
#, python-format
msgid "Password must be shorter than %d characters"
msgstr "口令必须短于 %d 个字符"

#: ../server/rhnUser.py:644
#, python-format
msgid "password contains character `%s'"
msgstr "口令包含字符 `%s'"

#: ../server/rhnUser.py:651
#, python-format
msgid "username should be at least %d characters long"
msgstr "用户名长度应至少为 %d 个字符"

#: ../server/rhnUser.py:662
#, python-format
msgid "Cannot register usernames ending with %s"
msgstr "无法注册以 %s 结尾的用户名"

#: ../server/apacheAuth.py:66
#, python-format
msgid "incomplete proxy authentication token: %s"
msgstr "不完整的代理身份验证令牌：%s"

#: ../server/apacheAuth.py:84
#, python-format
msgid "Sent proxy signature %s does not match ours %s."
msgstr "发送的代理签名 %s 与我们的 %s 不匹配。"

#: ../server/apacheAuth.py:119
msgid "declined proxy authentication"
msgstr "已拒绝代理身份验证"

#: ../server/apacheRequest.py:59
#, python-format
msgid "Invalid request received (%s)."
msgstr "收到的请求无效 (%s)。"

#: ../server/apacheRequest.py:120
#, python-format
msgid ""
"IMPORTANT MESSAGE FOLLOWS:\n"
"%s"
msgstr ""
"重要消息如下：\n"
"%s"

#: ../server/apacheRequest.py:149
#, python-format
msgid ""
"While running '%s': caught\n"
"%s : %s\n"
msgstr ""
"运行 '%s' 时捕获到\n"
"%s：%s\n"

#: ../server/apacheRequest.py:606
#, python-format
msgid "Invalid URI %s"
msgstr "无效的 URI %s"

#: ../server/importlib/userAuth.py:98
msgid "You are not authorized to manage packages in the null org"
msgstr "未授权您管理 null 组织中的软件包"

#: ../server/importlib/userAuth.py:103
#, python-format
msgid "You are not allowed to manage packages in the %s org"
msgstr "不允许您管理 %s 组织中的软件包"

#: ../server/importlib/userAuth.py:121
msgid "You are not allowed to perform administrative tasks"
msgstr "不允许您执行管理任务"

#: ../server/importlib/userAuth.py:144
#, python-format
msgid ""
"You are not allowed to manage channel %s, or that channel does not exist"
msgstr "不允许您管理频道 %s 或不存在的频道"

#: ../server/importlib/userAuth.py:204
#, python-format
msgid ""
"\n"
"               %s Account has been deactivated on this server.\n"
"               Please contact your Org administrator for more help."
msgstr ""
"\n"
"               已在此服务器上停用 %s 帐户。\n"
"               请联系您的组织管理员取得更多帮助。"

#: ../server/handlers/sat/auth.py:45
msgid "ISS is disabled on this server."
msgstr "已在此服务器上禁用 ISS。"

#: ../server/handlers/sat/auth.py:50
#, python-format
msgid "Server \"%s\" is not enabled for ISS."
msgstr "未为 ISS 启用服务器 \"%s\"。"

#: ../server/handlers/app/packages.py:192
#: ../server/handlers/xmlrpc/registration.py:217
#: ../server/handlers/xmlrpc/registration.py:1170
#: ../server/handlers/xmlrpc/registration.py:1309
#: ../server/configFilesHandler.py:129
#, python-format
msgid ""
"\n"
"                   %s Account has been deactivated on this server.\n"
"                   Please contact your Org administrator for more help."
msgstr ""
"\n"
"                   已在此服务器上停用 %s 帐户。\n"
"                   请联系您的组织管理员取得更多帮助。"

#: ../server/handlers/xmlrpc/proxy.py:65
#, python-format
msgid "SUSE Manager Proxy service not enabled for server profile: \"%s\""
msgstr "未为服务器配置文件启用 SUSE Manager Proxy 服务：\"%s\""

#: ../server/handlers/xmlrpc/proxy.py:85
msgid "Invalid session key"
msgstr "无效会话密钥"

#: ../server/handlers/xmlrpc/proxy.py:93
msgid "This server ID no longer exists"
msgstr "此服务器 ID 不再存在"

#: ../server/handlers/xmlrpc/queue.py:434
#, python-format
msgid "Invalid action value type %s (%s)"
msgstr "无效的操作值类型 %s (%s)"

#: ../server/handlers/xmlrpc/queue.py:462
#, python-format
msgid "Action %s does not belong to server %s"
msgstr "操作 %s 不属于服务器 %s"

#: ../server/handlers/xmlrpc/up2date.py:233
#, python-format
msgid "Invalid value %s (%s)"
msgstr "无效的值 %s (%s)"

#: ../server/handlers/xmlrpc/scap.py:104
msgid "Invalid system_id/action_id pair."
msgstr "无效的 system_id/action_id 对。"

#: ../server/handlers/xmlrpc/errata.py:64
#, python-format
msgid "Expected a package name, not: %s"
msgstr "预期需要提供软件包名称，而不是：%s"

#: ../server/handlers/xmlrpc/errata.py:115
#, python-format
msgid "Expected a package, not: %s"
msgstr "预期需要提供软件包，而不是：%s"

#: ../server/handlers/xmlrpc/registration.py:196
msgid "Required data missing"
msgstr "缺少必需的数据"

#: ../server/handlers/xmlrpc/registration.py:200
msgid "Required members missing"
msgstr "缺少必需的成员"

#: ../server/handlers/xmlrpc/registration.py:209
msgid "Attempt to register a system to an invalid username"
msgstr "尝试将系统注册到无效的用户名"

#: ../server/handlers/xmlrpc/registration.py:841
msgid "Invalid system release version requested"
msgstr "请求了无效的系统发行版"

#: ../server/handlers/xmlrpc/registration.py:1065
msgid ""
"Unable to find a valid network interface, both ipaddr and ip6addr not found."
msgstr "找不到有效的网络接口，ipaddr 和 ip6addr 均未找到。"

#: ../server/handlers/xmlrpc/registration.py:1117
#, python-brace-format
msgid "{PRODUCT_NAME} Welcome Message"
msgstr "{PRODUCT_NAME} 欢迎消息"

#: ../server/handlers/xmlrpc/registration.py:1127
msgid "Privacy Statement"
msgstr "隐私声明"

#: ../server/handlers/xmlrpc/registration.py:1148
msgid "Expected a dictionary as a product argument"
msgstr "预期需要提供一个字典作为产品参数"

#: ../server/handlers/xmlrpc/registration.py:1376
#, python-format
msgid "Invalid value '%s' for %s (%s)"
msgstr "值 '%s'（为 %s (%s) 提供）无效"

#: ../server/handlers/applet/applet.py:78
#, python-brace-format
msgid "Your system was not found in the {PRODUCT_NAME} database"
msgstr "在 {PRODUCT_NAME} 数据库中未找到您的系统"

#: ../server/rhnChannel.py:1999
#, python-format
msgid ""
"Your account does not have access to any channels matching "
"(release='%(release)s', arch='%(arch)s')%(www_activation)s"
msgstr ""
"您的帐户无权访问与 (release='%(release)s', "
"arch='%(arch)s')%(www_activation)s 匹配的任何频道"

#: ../server/rhnChannel.py:2014
#, python-format
msgid "Insufficient subscription permissions for release (%s, %s"
msgstr "订阅权限不足，无法获取发行版 (%s, %s"

#. Various messages that can be reused
#.
#. bretm 02/07/2007 -- when we have better old-client documentation, probably
#. will be safe to get rid of all this crap
#: ../server/rhnChannel.py:2278 ../server/rhnChannel.py:2293
msgid "System Registered but Inactive"
msgstr "系统已注册但处于非活动状态"

#: ../server/rhnChannel.py:2279
#, python-format
msgid ""
"\n"
"Invalid Architecture and OS release combination (%s, %s).\n"
"Your system has been registered, but will not receive updates\n"
"because it could not be subscribed to a base channel.\n"
"Please contact your organization administrator for assistance.\n"
msgstr ""
"\n"
"体系结构和操作系统发行版的组合无效 (%s, %s)。\n"
"您的系统已注册，但不会接收更新，\n"
"因为它无法订阅基础频道。\n"
"请联系您的组织管理员以取得帮助。\n"

#: ../server/rhnChannel.py:2286
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but is not yet entitled\n"
"  to service.  To entitle this system to service, login to the web site at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""
"\n"
"  已成功注册此系统，但尚未为其赋予\n"
"服务权利。要为此系统赋予服务权利，请登录网站：\n"
"\n"
"  %(entitlement_url)s\n"

#: ../server/rhnChannel.py:2294
#, python-format
msgid ""
"\n"
"  This system has been successfully registered, but no service entitlements\n"
"  were available.  To entitle this system to service, login to the web site "
"at:\n"
"\n"
"  %(entitlement_url)s\n"
msgstr ""
"\n"
"  此系统已成功注册，但没有可用的\n"
"服务权利。要为此系统赋予服务权利，请登录网站：\n"
"\n"
"  %(entitlement_url)s\n"

#: ../server/rhnPackage.py:49 ../server/rhnPackage.py:87
#: ../server/rhnPackage.py:107 ../server/rhnPackage.py:158
#, python-format
msgid "Invalid RPM package %s requested"
msgstr "请求的 RPM 软件包 %s 无效"

#: ../server/rhnPackage.py:112
msgid "Package not found"
msgstr "找不到软件包"

#: ../server/rhnHandler.py:62
msgid "Please run rhn_register as root on this client"
msgstr "请在此客户端中以 root 身份运行 rhn_register"

#: ../server/rhnHandler.py:75
#, python-format
msgid "Service not enabled for system profile: \"%s\""
msgstr "未为系统配置文件启用服务：\"%s\""

#. 0-999: Red Hat client/client-like interaction errors:
#: ../common/rhnException.py:53
msgid "This does not appear to be a valid username."
msgstr "这似乎不是有效的用户名。"

#: ../common/rhnException.py:54
msgid "Invalid username and password combination."
msgstr "无效的用户名和口令组合。"

#: ../common/rhnException.py:55
msgid "This login is already taken, or the password is incorrect."
msgstr "此登录名已被使用，或者口令不正确。"

#: ../common/rhnException.py:56
msgid "Permission denied."
msgstr "权限被拒绝。"

#: ../common/rhnException.py:57
msgid "Object not found."
msgstr "找不到对象。"

#: ../common/rhnException.py:58
msgid "Invalid System Digital ID."
msgstr "无效的系统数字 ID。"

#: ../common/rhnException.py:59
msgid "Invalid System Credentials."
msgstr "无效的系统身份凭证。"

#: ../common/rhnException.py:60
msgid "Could not retrieve user data from database."
msgstr "无法从数据库检索用户数据。"

#: ../common/rhnException.py:61
msgid "Valid username required."
msgstr "必须填写有效用户名。"

#: ../common/rhnException.py:62
msgid "Valid password required."
msgstr "必须填写有效口令。"

#: ../common/rhnException.py:63
msgid "Minimum username length violation."
msgstr "最小用户名长度违规。"

#: ../common/rhnException.py:64
msgid "Minimum password length violation."
msgstr "最小口令长度违规。"

#: ../common/rhnException.py:65
msgid "The username contains invalid characters."
msgstr "用户名包含无效字符。"

#: ../common/rhnException.py:66
msgid "File not found."
msgstr "找不到文件。"

#: ../common/rhnException.py:67
msgid "Architecture and OS version combination is not supported."
msgstr "不支持该体系结构和操作系统版本组合。"

#: ../common/rhnException.py:68
msgid "Could not retrieve system data from database."
msgstr "无法从数据库检索系统数据。"

#: ../common/rhnException.py:69
msgid "Invalid arguments passed to function."
msgstr "向函数传递了无效参数。"

#: ../common/rhnException.py:70
msgid "Unable to retrieve requested entry."
msgstr "无法检索请求的项。"

#: ../common/rhnException.py:71
msgid "Could not update database entry."
msgstr "无法更新数据库项。"

#: ../common/rhnException.py:72
msgid "Unsupported server architecture."
msgstr "不支持的服务器体系结构。"

#: ../common/rhnException.py:73
#, python-format
msgid ""
"\n"
"     The anonymous server functionality is no longer available.\n"
"\n"
"     Please re-register this system by running mgr_register as root.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable the service for this "
"system.\n"
"     "
msgstr ""
"\n"
"     匿名服务器功能不再可用。\n"
"\n"
"     请以 root 身份运行 mgr_register 以重新注册此系统。\n"
"     请访问 https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     或者在 https://%(hostname)s 上登录，然后在 \"概览\" 选项卡中\n"
"     选择 \"订阅管理\" 以便为此系统启用服务。\n"
"     "

#: ../common/rhnException.py:81
msgid "Record not available in the database."
msgstr "数据库中未提供记录。"

#: ../common/rhnException.py:82
msgid "Invalid value for entry."
msgstr "项的值无效。"

#: ../common/rhnException.py:83
#, python-format
msgid ""
"\n"
"     This system does not have a valid entitlement for SUSE Manager.\n"
"     Please visit https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     or login at https://%(hostname)s, and from the \"Overview\" tab,\n"
"     select \"Subscription Management\" to enable the service for this "
"system.\n"
"     "
msgstr ""
"\n"
"     此系统没有 SUSE Manager 的有效权利。\n"
"     请访问 https://%(hostname)s/rhn/systems/SystemEntitlements.do\n"
"     或者在 https://%(hostname)s 上登录，然后在 \"概览\" 选项卡中\n"
"     选择 \"订阅管理\" 以便为此系统启用服务。\n"
"     "

#: ../common/rhnException.py:89
msgid "Channel error"
msgstr "频道错误"

#: ../common/rhnException.py:90
msgid "Client session token is invalid."
msgstr "客户端会话令牌无效。"

#: ../common/rhnException.py:91
msgid "Client session token has expired."
msgstr "客户端会话令牌已失效。"

#: ../common/rhnException.py:92
msgid "You are not authorized to retrieve the requested object."
msgstr "未授权您检索请求的对象。"

#: ../common/rhnException.py:93
msgid "Invalid action"
msgstr "无效操作"

#: ../common/rhnException.py:94
msgid "You are not allowed to perform administrative tasks on this system."
msgstr "不允许您在此系统上执行管理任务。"

#: ../common/rhnException.py:96
msgid "The system is already subscribed to the specified channel."
msgstr "系统已订阅指定的频道。"

#: ../common/rhnException.py:97
msgid "The system is not currently subscribed to the specified channel."
msgstr "系统目前未订阅指定的频道。"

#: ../common/rhnException.py:98
msgid "The specified channel does not exist."
msgstr "指定的频道不存在。"

#: ../common/rhnException.py:99
msgid "Invalid channel version."
msgstr "无效频道版本。"

#: ../common/rhnException.py:100
msgid ""
"\n"
"     User group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     user account. Please check with the organization administrator for "
"your\n"
"     account if the maximum number of users allowed to subscribe to server "
"needs\n"
"     to be changed.\n"
"     "
msgstr ""
"\n"
"     超过了用户组成员资格限制。\n"
"\n"
"     您帐户的当前设置不允许您添加另一个\n"
"     用户帐户。请与您帐户的组织管理员确认\n"
"     是否需要更改有权订阅服务器的最大用户\n"
"     数目。\n"
"     "

#: ../common/rhnException.py:108
msgid ""
"\n"
"     System group membership limits exceeded.\n"
"\n"
"     The current settings for your account do not allow you to add another\n"
"     system profile. Please check with the organization administrator for "
"your\n"
"     account for modifying the maximum number of system profiles that can "
"be\n"
"     subscribed to your account.\n"
"     "
msgstr ""
"\n"
"     超过了系统组成员资格限制。\n"
"\n"
"     您帐户的当前设置不允许您添加另一个\n"
"     系统配置文件。请咨询您帐户的组织管理员\n"
"     确认来修改可订阅您帐户的最大系统\n"
"     配置文件数目。\n"
"     "

#: ../common/rhnException.py:116
msgid ""
"\n"
"     Invalid architecture.\n"
"\n"
"     The architecture of the package is not supported by\n"
"     "
msgstr ""
"\n"
"     体系结构无效。\n"
"\n"
"     软件包的体系结构不受以下对象的支持：\n"
"     "

#: ../common/rhnException.py:121
msgid "Invalid RPM header"
msgstr "无效的 RPM 头"

#: ../common/rhnException.py:122
msgid ""
"\n"
"    This system is already registered as a Salt Minion. If you want to "
"register it as a traditional client\n"
"    please delete it first via the web UI or API and then register it using "
"the traditional tools.\n"
"    "
msgstr ""
"\n"
"    此系统已注册为 Salt 受控端。如果您想要将其注册为传统客户端，\n"
"    请先通过 Web UI 或 API 将其删除，然后使用传统工具注册。\n"
"    "

#. For the uploading tools
#: ../common/rhnException.py:127
msgid "Invalid information uploaded to the server"
msgstr "向服务器上载了无效信息"

#: ../common/rhnException.py:128
msgid "Error uploading network interfaces configuration."
msgstr "上载网络接口配置时出错。"

#: ../common/rhnException.py:129
msgid ""
"\n"
"     Package Upload Failed due to uniqueness constraint violation.\n"
"     Make sure the package does not have any duplicate dependencies or\n"
"     does not already exists on the server\n"
"     "
msgstr ""
"\n"
"     由于违反唯一性约束，软件包上载失败。\n"
"     请确保该软件包不包含任何重复依赖项，或者\n"
"     尚不存在于服务器上\n"
"     "

#: ../common/rhnException.py:134
msgid ""
"\n"
"     The --force mgrpush option is disabled on this server.\n"
"     Please contact your SUSE Manager administrator for more help.\n"
"     "
msgstr ""
"\n"
"     已在此服务器上禁用 --force mgrpush 选项。\n"
"     请联系您的 SUSE Manager 管理员取得更多帮助。\n"
"     "

#. 60-70: token errors
#: ../common/rhnException.py:140
msgid ""
"\n"
"     The activation token specified could not be found on the server.\n"
"     Please retry with a valid key.\n"
"     "
msgstr ""
"\n"
"     在服务器上找不到指定的激活令牌。\n"
"     请使用有效密钥重试。\n"
"     "

#: ../common/rhnException.py:144
msgid "Too many systems registered using this registration token"
msgstr "使用此注册令牌注册了过多的系统"

#: ../common/rhnException.py:145
msgid "Token contains invalid, obsoleted or insufficient settings"
msgstr "令牌包含无效、已过时或不充分的设置"

#: ../common/rhnException.py:146
msgid "Conflicting activation tokens"
msgstr "有冲突的激活令牌"

#. 70-80: channel subscription errors
#: ../common/rhnException.py:149
msgid ""
"\n"
"     No matching base channel found for your system.\n"
"     "
msgstr ""
"\n"
"     未找到与您的系统匹配的基础频道。\n"
"     "

#: ../common/rhnException.py:152
msgid ""
"\n"
"     You do not have subscription permission to the designated channel.\n"
"     Please refer to your organization's channel or organization\n"
"     administrators for further details.\n"
"     "
msgstr ""
"\n"
"     您对指定的频道没有订阅权限。\n"
"     请咨询您组织的频道管理员或\n"
"     组织管理员以了解更多详细。\n"
"     "

#: ../common/rhnException.py:157
msgid "You can not unsubscribe from base channel."
msgstr "无法取消订阅基础频道。"

#: ../common/rhnException.py:158
msgid "SUSE Manager or Proxy channel can not be subscribed."
msgstr "无法订阅 SUSE Manager 或代理频道。"

#. 80-90: server group errors
#: ../common/rhnException.py:161
msgid "There was an error while trying to join the system to its groups"
msgstr "尝试将系统加入其组时出错"

#. 90-100: entitlement errors
#: ../common/rhnException.py:164
msgid "Unable to entitle system"
msgstr "无法为系统赋权"

#. 100-109: e-mail and uuid related faults
#: ../common/rhnException.py:167
msgid "Maximum e-mail length violation."
msgstr "最大电子邮件长度违规。"

#: ../common/rhnException.py:168
msgid "This system has been previously registered."
msgstr "此系统在过去已注册。"

#: ../common/rhnException.py:169
msgid "Invalid username"
msgstr "无效用户名"

#. 140-159 applet errors
#: ../common/rhnException.py:172
msgid "Unable to look up server"
msgstr "无法查找服务器"

#. 160-179: OSAD errors
#: ../common/rhnException.py:175
msgid "Required argument is missing"
msgstr "缺少必需的参数"

#. 600-699: RHEL5+ EN errors
#: ../common/rhnException.py:178
msgid "No entitlement information tied to hardware"
msgstr "没有任何权利信息与硬件相关联"

#: ../common/rhnException.py:179
msgid "Installation number is not entitling"
msgstr "安装号未赋权"

#. 700-799: Additional user input verification errors.
#: ../common/rhnException.py:182
msgid "Maximum username length violation"
msgstr "最大用户名长度违规"

#: ../common/rhnException.py:183
msgid "Maximum password length violation"
msgstr "最大口令长度违规"

#: ../common/rhnException.py:184
msgid "This user has read only API access. Action denied."
msgstr "此用户拥有只读 API 访问权限。操作被拒绝。"

#: ../common/rhnException.py:186
msgid "System Name cannot be less than 1 character"
msgstr "系统名不能短于 1 个字符"

#. 1000-1999: Proxy specific errors:
#. issued by a Proxy to the client
#: ../common/rhnException.py:190
msgid "SUSE Manager Proxy error."
msgstr "SUSE Manager Proxy 错误。"

#: ../common/rhnException.py:191
msgid "SUSE Manager Proxy unable to login."
msgstr "SUSE Manager Proxy 无法登录。"

#. issued by a SUSE Manager Server/Satellite to the proxy
#: ../common/rhnException.py:193
msgid ""
"\n"
"     SUSE Manager Proxy system ID does not match a Spacewalk Proxy Server\n"
"     in the database.\n"
"     "
msgstr ""
"\n"
"     SUSE Manager Proxy 系统 ID 与数据库中的 Spacewalk 代理服务器\n"
"     不匹配。\n"
"     "

#: ../common/rhnException.py:197
msgid "SUSE Manager Proxy session token is invalid."
msgstr "SUSE Manager Proxy 会话令牌无效。"

#: ../common/rhnException.py:198
msgid "SUSE Manager Proxy session token has expired."
msgstr "SUSE Manager Proxy 会话令牌已失效。"

#. 2000-2999: Red Hat Satellite specific errors:
#: ../common/rhnException.py:202
msgid ""
"\n"
"      user creation is not allowed via mgr_register;\n"
"     please contact your sysadmin to have your account created.\n"
"     "
msgstr ""
"\n"
"      不允许通过 mgr_register 创建用户；\n"
"     请联系您的系统管理员来创建您的帐户。\n"
"     "

#: ../common/rhnException.py:206
msgid ""
"\n"
"     This SUSE Manager server is not allowed to use Inter Server Sync on "
"this server\n"
"     "
msgstr ""
"\n"
"     不允许此 SUSE Manager 服务器在此服务器上使用服务器间同步\n"
"     "

#: ../common/rhnException.py:209
msgid ""
"\n"
"     Inter Server Sync is disabled on this SUSE Manager Server.\n"
"     "
msgstr ""
"\n"
"     已在此 SUSE Manager Server 上禁用服务器间同步。\n"
"     "

#. 3000-3999: XML dumper errors:
#: ../common/rhnException.py:214
msgid "Invalid datatype passed"
msgstr "传递了无效的数据类型"

#: ../common/rhnException.py:215
msgid "Unable to retrieve channel"
msgstr "无法检索频道"

#: ../common/rhnException.py:216
msgid "Unable to retrieve package"
msgstr "无法检索软件包"

#: ../common/rhnException.py:217
msgid "Unable to retrieve erratum"
msgstr "无法检索勘误"

#: ../common/rhnException.py:218
msgid "File is missing"
msgstr "缺少文件"

#: ../common/rhnException.py:219
msgid "Function retrieval error"
msgstr "函数检索错误"

#: ../common/rhnException.py:220
msgid "Function execution error"
msgstr "函数执行错误"

#: ../common/rhnException.py:221
msgid "Missing version string"
msgstr "缺少版本字符串"

#: ../common/rhnException.py:222
msgid "Invalid version string"
msgstr "无效的版本字符串"

#: ../common/rhnException.py:223
msgid "Mismatching versions"
msgstr "不匹配的版本"

#: ../common/rhnException.py:224
msgid "Invalid channel version"
msgstr "无效的频道版本"

#: ../common/rhnException.py:225
msgid "No comps file for channel"
msgstr "频道没有 comps 文件"

#: ../common/rhnException.py:226
msgid "Unable to retrieve comps file"
msgstr "无法检索 comps 文件"

#. 4000 - 4999: config management errors
#: ../common/rhnException.py:229
msgid "Configuration action missing"
msgstr "缺少配置操作"

#: ../common/rhnException.py:230
msgid "File too large"
msgstr "文件太大"

#: ../common/rhnException.py:231
msgid "File contains binary data"
msgstr "文件包含二进制数据"

#: ../common/rhnException.py:232
msgid "Configuration channel is not empty"
msgstr "配置频道不为空"

#: ../common/rhnException.py:233
msgid "Permission error"
msgstr "权限错误"

#: ../common/rhnException.py:234
msgid "Content missing for configuration file"
msgstr "配置文件缺少内容"

#: ../common/rhnException.py:235
msgid "Template delimiters not specified"
msgstr "未指定模板分隔符"

#: ../common/rhnException.py:236
msgid "Configuration channel does not exist"
msgstr "配置频道不存在"

#: ../common/rhnException.py:237
msgid "Configuration channel already exists"
msgstr "配置频道已存在"

#: ../common/rhnException.py:238
msgid "File missing from configuration channel"
msgstr "配置频道中缺少文件"

#: ../common/rhnException.py:239
msgid "Different revision of this file is uploaded"
msgstr "上载了此文件的不同版本"

#: ../common/rhnException.py:240
msgid "File already uploaded to configuration channel"
msgstr "文件已上载到配置频道"

#: ../common/rhnException.py:241
msgid "File size exceeds remaining quota space"
msgstr "文件大小超过了剩余的配额空间"

#: ../common/rhnException.py:242
msgid "Full path of file must be specified"
msgstr "必须指定文件的完整路径"

#: ../common/rhnException.py:243
msgid "Invalid revision number"
msgstr "无效的修订版号"

#: ../common/rhnException.py:244
msgid "Cannot compare files of different file type"
msgstr "无法比较不同类型的文件"

#. 5100 - 5199: scap results reporting error
#: ../common/rhnException.py:247
msgid "SCAP results file transfer is invalid or incomplete"
msgstr "传输的 SCAP 结果文件无效或不完整"

#: ../common/rhnException.py:248
msgid "Error composing directory path for detailed SCAP results"
msgstr "编写详细 SCAP 结果的目录路径时出错"

#: ../common/rhnException.py:249
msgid "Error composing file path for detailed SCAP results"
msgstr "编写详细 SCAP 结果的文件路径时出错"

#: ../common/rhnException.py:250
msgid "Invalid content encoding"
msgstr "无效的内容编码"

#: ../common/rhnException.py:297
msgid ""
"\n"
"     An error has occurred while processing your request. If this problem\n"
"     persists please enter a bug report at scc.suse.com.\n"
"     If you choose to submit the bug report, please be sure to include\n"
"     details of what you were trying to do when this error occurred and\n"
"     details on how to reproduce this problem.\n"
msgstr ""
"\n"
"     处理您的请求时出错。如果此问题持续出现，\n"
"     请在 scc.suse.com 上输入 bug 报告。\n"
"     如果您选择提交 bug 报告，请务必详细\n"
"     说明发生此错误时您正在尝试执行哪项\n"
"     操作，并详细告知如何重现此问题。\n"

#: ../common/rhnException.py:349
#, python-format
msgid ""
"Error Message:\n"
"    %s\n"
msgstr ""
"错误消息：\n"
"    %s\n"

#: ../common/rhnException.py:351
#, python-format
msgid "Error Class Code: %s\n"
msgstr "错误类代码：%s\n"

#: ../common/rhnException.py:354
#, python-format
msgid "Error Class Info: %s\n"
msgstr "错误类信息：%s\n"

#: ../common/rhnException.py:356
#, python-format
msgid "Explanation: %s"
msgstr "说明：%s"

#: ../common/rhnTB.py:205
#, python-format
msgid "ERROR: %s %s: %s"
msgstr "错误：%s %s：%s"

#: ../common/rhnTB.py:207
#, python-format
msgid "TRACEBACK: %s"
msgstr "回溯：%s"

#: ../satellite_tools/disk_dumper/iss.py:1294
#: ../satellite_tools/disk_dumper/iss.py:1298
#, python-format
msgid "format of %s should be at least YYYYMMDD.\n"
msgstr "%s 至少应采用 YYYYMMDD 格式。\n"

#: ../satellite_tools/satsync.py:258
#, python-format
msgid "No handler for step %s"
msgstr "步骤 %s 没有处理程序"

#. Try one more time - this time it should be faster since
#. everything should be cached
#: ../satellite_tools/satsync.py:270
msgid "Environment changed, trying again..."
msgstr "环境已更改，正在重试..."

#: ../satellite_tools/satsync.py:277
msgid "ERROR: Encountered IntegrityError: \n"
msgstr "错误：遇到了 IntegrityError： \n"

#: ../satellite_tools/satsync.py:285
msgid "Repeated failures"
msgstr "反复失败"

#: ../satellite_tools/satsync.py:290
#, python-format
msgid ""
"    Import complete:\n"
"        Begin time: %s\n"
"        End time:   %s\n"
"        Elapsed:    %s\n"
"          "
msgstr ""
"    导入已完成：\n"
"        开始时间：%s\n"
"        结束时间：%s\n"
"        已用时间：%s\n"
"          "

#: ../satellite_tools/satsync.py:311
msgid "hours"
msgstr "小时"

#: ../satellite_tools/satsync.py:311
msgid "minutes"
msgstr "分钟"

#: ../satellite_tools/satsync.py:311
msgid "seconds"
msgstr "秒"

#: ../satellite_tools/satsync.py:357
msgid ""
"ERROR: The dump is missing package data, use --no-rpms to skip this step or "
"fix the content to include package data."
msgstr ""
"错误：转储中缺少软件包数据，请使用 --no-rpms 跳过此步骤，或者修复内容以包含软"
"件包数据。"

#. the orgs() method doesn't exist; that's fine we just
#. won't sync the orgs
#: ../satellite_tools/satsync.py:404
msgid "The SUSE Manager master does not support syncing orgs data."
msgstr "SUSE Manager 主服务器不支持同步组织数据。"

#: ../satellite_tools/satsync.py:404
msgid "Skipping..."
msgstr "正在跳过..."

#: ../satellite_tools/satsync.py:439 ../satellite_tools/reposync.py:118
msgid "+++ sending log as an email +++"
msgstr "+++ 正在以电子邮件形式发送日志 +++"

#: ../satellite_tools/satsync.py:442
#, python-format
msgid "SUSE Manager Inter Server sync. report from %s"
msgstr "来自 %s 的 SUSE Manager 服务器间同步报告"

#: ../satellite_tools/satsync.py:449 ../satellite_tools/reposync.py:131
msgid "+++ email requested, but there is nothing to send +++"
msgstr "+++ 已请求电子邮件，但没有可发送的内容 +++"

#: ../satellite_tools/satsync.py:520
msgid " - file-system synchronization"
msgstr " - 文件系统同步"

#: ../satellite_tools/satsync.py:532 ../satellite_tools/satsync.py:540
msgid " - live synchronization"
msgstr " - 在线同步"

#: ../satellite_tools/satsync.py:533
#, python-brace-format
msgid ""
"ERROR: Live content synchronizing with RHN Classic Hosted is no longer "
"supported.\n"
"Please use the cdn-sync command instead unless you are attempting to sync "
"from another {PRODUCT_NAME} via Inter-Server-Sync (ISS), or from local "
"content on disk via Channel Dump ISOs."
msgstr ""
"错误：不再支持使用 RHN Classic Hosted 进行在线内容同步。\n"
"除非您要尝试通过服务器间同步 (ISS) 从另一个 {PRODUCT_NAME} 同步，或者通过频道"
"转储 ISO 从磁盘上的本地内容同步，否则请改用 cdn-sync 命令。"

#: ../satellite_tools/satsync.py:541
#, python-format
msgid "   url: %s"
msgstr "   URL：%s"

#: ../satellite_tools/satsync.py:542
#, python-format
msgid "   debug/output level: %s"
msgstr "   调试/输出级别：%s"

#: ../satellite_tools/satsync.py:552
msgid "ERROR: this server must be registered with SUSE Manager."
msgstr "错误：必须将此服务器注册到 SUSE Manager。"

#: ../satellite_tools/satsync.py:574
#, python-format
msgid "Retrieving / parsing %s data"
msgstr "正在检索/分析 %s 数据"

#: ../satellite_tools/satsync.py:584 ../satellite_tools/satsync.py:599
msgid "*** SYSTEM INTERRUPT CALLED ***"
msgstr "*** 已调用系统中断 ***"

#: ../satellite_tools/satsync.py:592
msgid "ERROR: fatal parser exception occurred "
msgstr "错误：发生了严重的分析器异常 "

#: ../satellite_tools/satsync.py:593
#, python-format
msgid "(line: %s, col: %s msg: %s)"
msgstr "（行：%s，列：%s，消息：%s）"

#: ../satellite_tools/satsync.py:597
#, python-format
msgid "ERROR: parser exception occurred: %s"
msgstr "错误：发生了分析器异常：%s"

#: ../satellite_tools/satsync.py:602
msgid "ERROR: exception (during parse) occurred: "
msgstr "错误：（在分析期间）发生异常： "

#: ../satellite_tools/satsync.py:603
#, python-format
msgid ""
"   Encountered some errors with %s data (see logs (%s) for more information)"
msgstr "   %s 数据出现了一些错误（有关详细信息，请查看日志 (%s)）"

#: ../satellite_tools/satsync.py:605
#, python-format
msgid "   Encountered some errors with %s data:"
msgstr "   %s 数据出现了一些错误："

#: ../satellite_tools/satsync.py:606
#, python-format
msgid "   ------- %s PARSE/IMPORT ERROR -------"
msgstr "   ------- %s 分析/导入错误 -------"

#: ../satellite_tools/satsync.py:608
msgid "   ---------------------------------------"
msgstr "   ---------------------------------------"

#: ../satellite_tools/satsync.py:611
#, python-format
msgid "%s data complete"
msgstr "%s 数据完整"

#: ../satellite_tools/satsync.py:664
msgid "Retrieving / parsing channel data"
msgstr "正在检索/分析频道数据"

#: ../satellite_tools/satsync.py:717
msgid "Channel data complete"
msgstr "频道数据完整"

#: ../satellite_tools/satsync.py:735
#, python-format
msgid "%10s import from %s"
msgstr "%10s 导入自 %s"

#: ../satellite_tools/satsync.py:738
#, python-format
msgid "%10s import from %s - %s"
msgstr "%10s 导入自 %s - %s"

#: ../satellite_tools/satsync.py:742
#, python-format
msgid "%10s"
msgstr "%10s"

#: ../satellite_tools/satsync.py:749
msgid "p"
msgstr "p"

#: ../satellite_tools/satsync.py:751
msgid "."
msgstr "."

#: ../satellite_tools/satsync.py:757
msgid "   p = previously imported/synced channel"
msgstr "   p = 以前导入/同步的频道"

#: ../satellite_tools/satsync.py:758
msgid "   . = channel not yet imported/synced"
msgstr "   . = 尚未导入/同步的频道"

#: ../satellite_tools/satsync.py:764
msgid "   e = channel no longer supported (end-of-service)"
msgstr "   e = 不再支持的频道（服务终止）"

#: ../satellite_tools/satsync.py:766
msgid "   ? = channel label invalid --- typo?"
msgstr "   ? = 频道标签无效 --- 拼写错误？"

#: ../satellite_tools/satsync.py:770
#, python-format
msgid "   %s:"
msgstr "   %s："

#: ../satellite_tools/satsync.py:771
#, python-format
msgid "      %s %-40s %4s %s"
msgstr "      %s %-40s %4s %s"

#: ../satellite_tools/satsync.py:772
msgid "base-channels"
msgstr "基础频道"

#: ../satellite_tools/satsync.py:785 ../satellite_tools/satsync.py:1619
msgid "NONE RELEVANT"
msgstr "无相关内容"

#: ../satellite_tools/satsync.py:807
msgid "end-of-service"
msgstr "服务终止"

#: ../satellite_tools/satsync.py:808
msgid "e"
msgstr "e"

#: ../satellite_tools/satsync.py:814
msgid "   typos:"
msgstr "   拼写错误："

#: ../satellite_tools/satsync.py:815
msgid "?"
msgstr "?"

#: ../satellite_tools/satsync.py:830
#, python-format
msgid "XXX: imported channels: %s"
msgstr "XXX：已导入频道：%s"

#: ../satellite_tools/satsync.py:831
#, python-format
msgid "XXX:   cached channels: %s"
msgstr "XXX：已缓存频道：%s"

#: ../satellite_tools/satsync.py:836
msgid "XXX: list channels called"
msgstr "XXX：已调用列出频道命令"

#: ../satellite_tools/satsync.py:854
msgid "ERROR: these channels either do not exist or are not available:"
msgstr "错误：这些频道不存在或者不可用："

#: ../satellite_tools/satsync.py:858
#, python-format
msgid "       (to see a list of channel labels: %s --list-channels)"
msgstr "       （要查看频道标签列表：%s --list-channels）"

#: ../satellite_tools/satsync.py:903
#, python-format
msgid "   Retrieving / parsing short package metadata: %s (%s)"
msgstr "   正在检索/分析短软件包元数据：%s (%s)"

#: ../satellite_tools/satsync.py:981
#, python-format
msgid "Diffing package metadata (what's missing locally?): %s"
msgstr "正在识别软件包元数据的差异（本地缺少哪些数据？）：%s"

#: ../satellite_tools/satsync.py:987 ../satellite_tools/satsync.py:1270
msgid "Diffing:    "
msgstr "正在识别差异：    "

#: ../satellite_tools/satsync.py:1004
msgid "ERROR: incremental dump skipped"
msgstr "错误：已跳过增量转储"

#: ../satellite_tools/satsync.py:1095
msgid "Downloading rpm packages"
msgstr "正在下载 RPM 软件包"

#: ../satellite_tools/satsync.py:1100
#, python-format
msgid "   Fetching any missing RPMs: %s (%s)"
msgstr "   正在提取任何缺少的 RPM：%s (%s)"

#: ../satellite_tools/satsync.py:1101 ../satellite_tools/satsync.py:1169
msgid "NONE MISSING"
msgstr "不缺少内容"

#: ../satellite_tools/satsync.py:1110
msgid "Processing rpm packages complete"
msgstr "RPM 软件包处理已完成"

#: ../satellite_tools/satsync.py:1137
msgid "Downloading package metadata"
msgstr "正在下载软件包元数据"

#: ../satellite_tools/satsync.py:1162
msgid "Downloading srpm packages"
msgstr "正在下载 SRPM 软件包"

#: ../satellite_tools/satsync.py:1168
#, python-format
msgid "   Fetching any missing SRPMs: %s (%s)"
msgstr "   正在提取任何缺少的 SRPM：%s (%s)"

#: ../satellite_tools/satsync.py:1265
#, python-format
msgid "Diffing source package metadata (what's missing locally?): %s"
msgstr "正在识别软件源包元数据的差异（本地缺少哪些数据？）：%s"

#: ../satellite_tools/satsync.py:1276
msgid "Downloading source package metadata"
msgstr "正在下载源软件包元数据"

#: ../satellite_tools/satsync.py:1354 ../satellite_tools/satsync.py:2043
#, python-format
msgid "Unable to save file %s: %s"
msgstr "无法保存文件 %s：%s"

#. for
#. Retried a number of times and it still failed; log the
#. file as being failed and move on
#: ../satellite_tools/satsync.py:1361
#, python-format
msgid "Failed to fetch file %s"
msgstr "无法提取文件 %s"

#: ../satellite_tools/satsync.py:1366
msgid "Downloading kickstartable trees metadata"
msgstr "正在下载 kickstart 树元数据"

#: ../satellite_tools/satsync.py:1381
msgid "Downloading kickstartable trees files"
msgstr "正在下载 kickstart 树文件"

#: ../satellite_tools/satsync.py:1520
#, python-format
msgid "Grabbing all patches for channel %s"
msgstr "正在抓取频道 %s 的所有补丁"

#: ../satellite_tools/satsync.py:1570
msgid "Downloading patch data"
msgstr "正在下载补丁数据"

#: ../satellite_tools/satsync.py:1572
msgid "Forcing download of all patch data for requested channels."
msgstr "正在强制下载所请求频道的所有补丁数据。"

#: ../satellite_tools/satsync.py:1587
msgid "Downloading patch data complete"
msgstr "下载补丁数据已完成"

#: ../satellite_tools/satsync.py:1592 ../satellite_tools/satsync.py:1613
msgid "Downloading:"
msgstr "正在下载："

#: ../satellite_tools/satsync.py:1595
msgid " - complete"
msgstr " - 完成"

#: ../satellite_tools/satsync.py:1640
msgid "Importing source package metadata"
msgstr "正在导入源软件包元数据"

#: ../satellite_tools/satsync.py:1643
msgid "Importing package metadata"
msgstr "正在导入软件包元数据"

#: ../satellite_tools/satsync.py:1651
msgid "Importing:  "
msgstr "正在导入：  "

#. not in the cache
#: ../satellite_tools/satsync.py:1719
msgid ""
"Package Not Found in Cache, Clear the Cache "
"to                                  Regenerate it."
msgstr ""
"在缓存中找不到软件包，请清除缓存                                  以重新生成"
"软件包。"

#: ../satellite_tools/satsync.py:1725
msgid "Importing channel patches"
msgstr "正在导入频道补丁"

#: ../satellite_tools/satsync.py:1730
#, python-format
msgid "Importing %s patches for channel %s."
msgstr "正在导入 %s 补丁（用于频道 %s）。"

#. Incomplete configuration
#: ../satellite_tools/satsync.py:2129
msgid "ERROR: server.mount_point not set in the configuration file"
msgstr "错误：未在配置文件中设置 server.mount_point"

#: ../satellite_tools/satsync.py:2133
#, python-format
msgid "ERROR: server.mount_point %s do not exist"
msgstr "错误：server.mount_point %s 不存在"

#: ../satellite_tools/satsync.py:2138
#, python-format
msgid "ERROR: path under server.mount_point (%s)  do not exist"
msgstr "错误：server.mount_point (%s) 下的路径不存在"

#: ../satellite_tools/satsync.py:2215
#, python-format
msgid "Commandline: %s"
msgstr "命令行：%s"

#: ../satellite_tools/satsync.py:2218
#, python-format
msgid ""
"DEBUG ONLY: max. batch-size for XML/database-import processing (1..%s).\"man "
"mgr-inter-sync\" for more information."
msgstr ""
"仅限调试：XML/数据库导入处理的最大批大小 (1..%s)。有关详细信息，请参见 \"man "
"mgr-inter-sync\"。"

#: ../satellite_tools/satsync.py:2221
msgid "alternative SSL CA Cert (fullpath to cert file)"
msgstr "备用 SSL CA 证书（证书文件的完整路径）"

#: ../satellite_tools/satsync.py:2223
msgid "process data for this channel only"
msgstr "仅处理此频道的数据"

#: ../satellite_tools/satsync.py:2225
msgid ""
"disk dump will be considered to be a full export; see \"man mgr-inter-sync\" "
"for more information."
msgstr ""
"磁盘转储将被视为完整导出内容；有关详细信息，请参见 \"man mgr-inter-sync\"。"

#: ../satellite_tools/satsync.py:2228
msgid "existing custom channels will also be synced (unless -c is used)"
msgstr "也会同步现有的自定义频道（除非使用 -c）"

#: ../satellite_tools/satsync.py:2230
#, python-format
msgid ""
"override debug level set in /etc/rhn/rhn.conf (which is currently set at %s)."
msgstr "覆盖 /etc/rhn/rhn.conf 中设置的调试级别（当前已在 %s 中设置）。"

#: ../satellite_tools/satsync.py:2232
#, python-format
msgid "requested version of XML dump (default: %s)"
msgstr "请求的 XML 转储版本（默认值：%s）"

#: ../satellite_tools/satsync.py:2234
msgid "e-mail a report of what was synced/imported"
msgstr "通过电子邮件发送已同步/导入内容的报告"

#: ../satellite_tools/satsync.py:2236
msgid "forcibly process all (not a diff of) patch metadata"
msgstr "强制处理所有补丁元数据（不处理有差异的元数据）"

#: ../satellite_tools/satsync.py:2238
msgid "Do not use an http proxy under any circumstances."
msgstr "在任何场合下都不使用 HTTP 代理。"

#: ../satellite_tools/satsync.py:2240
msgid "alternative http proxy (hostname:port)"
msgstr "备用 HTTP 代理（主机名:端口）"

#: ../satellite_tools/satsync.py:2242
msgid "alternative http proxy username"
msgstr "备用 HTTP 代理用户名"

#: ../satellite_tools/satsync.py:2244
msgid "alternative http proxy password"
msgstr "备用 HTTP 代理口令"

#: ../satellite_tools/satsync.py:2246
msgid "parent SUSE Manager to import content from"
msgstr "要从中导入内容的父 SUSE Manager"

#: ../satellite_tools/satsync.py:2248
msgid "list all available channels and exit"
msgstr "列出所有可用频道并退出"

#: ../satellite_tools/satsync.py:2250
msgid "help on all error codes mgr-inter-sync returns"
msgstr "有关 mgr-inter-sync 返回的所有错误代码的帮助"

#: ../satellite_tools/satsync.py:2252
msgid "source mount point for import - disk update only"
msgstr "用于导入的源装入点 - 仅限磁盘更新"

#: ../satellite_tools/satsync.py:2254
msgid "do not process patch data"
msgstr "不处理补丁数据"

#: ../satellite_tools/satsync.py:2256
msgid "do not process kickstart data (provisioning only)"
msgstr "不处理 kickstart 数据（仅置备）"

#: ../satellite_tools/satsync.py:2258
msgid "do not process full package metadata"
msgstr "不处理完整软件包元数据"

#: ../satellite_tools/satsync.py:2260
msgid "do not download, or process any RPMs"
msgstr "不下载，也不处理任何 RPM"

#: ../satellite_tools/satsync.py:2262
msgid "org to which the sync imports data. defaults to the admin account"
msgstr "同步操作要将数据导入到的组织。默认为管理员帐户"

#: ../satellite_tools/satsync.py:2264
msgid "print the configuration and exit"
msgstr "列显配置并退出"

#: ../satellite_tools/satsync.py:2266
msgid "alternative server with which to connect (hostname)"
msgstr "用于连接的备用服务器（主机名）"

#: ../satellite_tools/satsync.py:2268
msgid "synchronize to this step (man mgr-inter-sync for more info)"
msgstr "同步到此步骤（有关详细信息，请参见 man mgr-inter-sync）"

#: ../satellite_tools/satsync.py:2270
msgid "write complete data to tempfile before streaming to remainder of app"
msgstr "先将完整数据写入 tempfile，然后再流式传输到应用程序的剩余组件"

#: ../satellite_tools/satsync.py:2272
msgid "DEBUG ONLY: alternative path to digital system id"
msgstr "仅限调试：数字系统 ID 的备用路径"

#: ../satellite_tools/satsync.py:2274
msgid "alternative email address(es) for sync output (--email option)"
msgstr "用于同步输出的备用电子邮件地址（--email 选项）"

#: ../satellite_tools/satsync.py:2276
msgid "do not remove rpms when importing from local dump"
msgstr "从本地转储导入时不要去除 RPM"

#: ../satellite_tools/satsync.py:2278
msgid ""
"the fully qualified domain name of the master Satellite. Valid with --mount-"
"point only. Required if you want to import org data and channel permissions."
msgstr ""
"主服务器的从属服务器的完全限定域名。仅当与 --mount-point 结合使用时才有效。如"
"果您想要导入组织数据和频道权限，则必须指定此选项。"

#: ../satellite_tools/satsync.py:2288
#, python-format
msgid "ERROR: these arguments make no sense in this context (try --help): %s"
msgstr "错误：这些参数在此上下文中没有意义（请尝试 --help）：%s"

#. An SQL error is fatal... crash and burn
#: ../satellite_tools/satsync.py:2300
#, python-format
msgid "ERROR: Can't connect to the database: %s"
msgstr "错误：无法连接到数据库：%s"

#: ../satellite_tools/satsync.py:2301
msgid "ERROR: Check if your database is running."
msgstr "错误：检查您的数据库是否正在运行。"

#: ../satellite_tools/satsync.py:2336
#, python-format
msgid "ERROR: --debug-level takes an in integer value within the range %s."
msgstr "错误：--debug-level 采用 %s 范围内的整数值。"

#: ../satellite_tools/satsync.py:2338
msgid "  0  - little logging/messaging."
msgstr "  0  - 记录极少量的日志/显示极少量的消息。"

#: ../satellite_tools/satsync.py:2339
msgid "  1  - minimal logging/messaging."
msgstr "  1  - 记录少量的日志/显示少量的消息。"

#: ../satellite_tools/satsync.py:2340
msgid "  2  - normal level of logging/messaging."
msgstr "  2  - 常规日志记录/消息显示级别。"

#: ../satellite_tools/satsync.py:2341
msgid "  3  - lots of logging/messaging."
msgstr "  3  - 记录大量的日志/显示大量的消息。"

#: ../satellite_tools/satsync.py:2342
msgid "  4+ - excessive logging/messaging."
msgstr "  4  - 记录极大量的日志/显示极大量的消息。"

#: ../satellite_tools/satsync.py:2355
msgid "ERROR: The --master option is only valid with the --mount-point option"
msgstr "错误：--master 选项只在与 --mount-point 结合使用时才有效"

#: ../satellite_tools/satsync.py:2365
#, python-format
msgid "ERROR: Unable to lookup Org Id %s"
msgstr "错误：无法查找组织 ID %s"

#: ../satellite_tools/satsync.py:2374
msgid ""
"WARNING: --list-channels option overrides any --step option. --step ignored."
msgstr "警告：--list-channels 选项将覆盖任何 --step 选项。已忽略 --step。"

#: ../satellite_tools/satsync.py:2389
#, python-format
msgid ""
"ERROR: '%s' is not a valid step. See 'man mgr-inter-sync' for more detail."
msgstr "错误：'%s' 不是有效步骤。有关更多细节，请参见 'man mgr-inter-sync'。"

#: ../satellite_tools/satsync.py:2421
msgid ""
"ERROR: No channels currently imported; try mgr-inter-sync --list-channels; "
"then mgr-inter-sync -c chn0 -c chn1..."
msgstr ""
"错误：当前未导入任何频道；请尝试运行 mgr-inter-sync --list-channels；然后运"
"行 mgr-inter-sync -c chn0 -c chn1..."

#. int(None) --> TypeError
#. int('a')  --> ValueError
#: ../satellite_tools/satsync.py:2470 ../satellite_tools/satsync.py:2474
msgid "ERROR: --batch-size must have a value within the range: 1..50"
msgstr "错误：--batch-size 必须使用以下范围内的值：1...50"

#: ../satellite_tools/satsync.py:2482
#, python-format
msgid "ERROR: no such directory %s"
msgstr "错误：没有这种目录 %s"

#: ../satellite_tools/satsync.py:2487
msgid "Error Codes: Returned codes means:"
msgstr "错误代码：返回的代码表示："

#: ../satellite_tools/satsync.py:2488
msgid " -1  - Could not lock file or KeyboardInterrupt or SystemExit"
msgstr " -1  - 无法锁定文件，或者发生了 KeyboardInterrupt 或 SystemExit"

#: ../satellite_tools/satsync.py:2489
msgid "  0  - User interrupted or intentional exit"
msgstr "  0  - 用户已中断或者有意退出"

#: ../satellite_tools/satsync.py:2490
msgid "  1  - attempting to run more than one instance of mgr-inter-sync."
msgstr "  1  - 正在尝试运行 mgr-inter-sync 的多个实例。"

#: ../satellite_tools/satsync.py:2491
msgid "  2  - Unable to find synchronization tools."
msgstr "  2  - 找不到同步工具。"

#: ../satellite_tools/satsync.py:2492
msgid "  3  - a general socket exception occurred"
msgstr "  3  - 发生了一般性的套接字异常"

#: ../satellite_tools/satsync.py:2493
msgid "  4  - an SSL error occurred. Recheck your SSL settings."
msgstr "  4  - 发生了 SSL 错误。请再次检查您的 SSL 设置。"

#: ../satellite_tools/satsync.py:2494
msgid "  5  - ISS error"
msgstr "  5  - ISS 错误"

#: ../satellite_tools/satsync.py:2495
msgid "  6  - unhandled exception occurred"
msgstr "  6  - 发生了未经处理的异常"

#: ../satellite_tools/satsync.py:2496
msgid "  7  - unknown sync error"
msgstr "  7  - 未知同步错误"

#: ../satellite_tools/satsync.py:2497
msgid "  8  - ERROR: must be root to execute"
msgstr "  8  - 错误：只有 root 用户可以执行"

#: ../satellite_tools/satsync.py:2498
msgid "  9  - rpclib fault during synchronization init"
msgstr "  9  - 执行同步初始化期间发生 rpclib 错误"

#: ../satellite_tools/satsync.py:2499
msgid "  10 - synchronization init error"
msgstr "  10 - 同步初始化错误"

#: ../satellite_tools/satsync.py:2500
msgid "  11 - Error parsing XML stream"
msgstr "  11 - 分析 XML 流时出错"

#: ../satellite_tools/satsync.py:2501
msgid "  12 - Channel do not exist"
msgstr "  12 - 频道不存在"

#: ../satellite_tools/satsync.py:2502
msgid "  13 - SQL error during importing package metadata"
msgstr "  13 - 导入软件包元数据期间发生 SQL 错误"

#: ../satellite_tools/satsync.py:2503
msgid "  14 - SQL error during linking channel packages"
msgstr "  14 - 链接频道软件包期间发生 SQL 错误"

#: ../satellite_tools/satsync.py:2504
msgid "  15 - SQL error during xml processing"
msgstr "  15 - 处理 XML 期间发生 SQL 错误"

#: ../satellite_tools/satsync.py:2505
msgid "  16 - server.mount_point not set in the configuration file"
msgstr "  16 - 未在配置文件中设置 server.mount_point"

#: ../satellite_tools/satsync.py:2506
msgid ""
"  17 - SQL error during retrieving the channels already imported in the SUSE "
"Manager database"
msgstr "  17 - 检索已导入到 SUSE Manager 数据库的频道期间发生 SQL 错误"

#: ../satellite_tools/satsync.py:2507
msgid "  18 - Wrong db connection string in rhn.conf"
msgstr "  18 - rhn.conf 中的数据库连接错误"

#: ../satellite_tools/satsync.py:2508
msgid "  19 - Bad arguments"
msgstr "  19 - 错误的参数"

#: ../satellite_tools/satsync.py:2509
msgid "  20 - Could not connect to db."
msgstr "  20 - 无法连接到数据库。"

#: ../satellite_tools/satsync.py:2510
msgid "  21 - Bad debug level"
msgstr "  21 - 错误的调试级别"

#: ../satellite_tools/satsync.py:2511
msgid "  22 - Not valid step"
msgstr "  22 - 步骤无效"

#: ../satellite_tools/satsync.py:2512
msgid "  24 - no such file"
msgstr "  24 - 没有这种文件"

#: ../satellite_tools/satsync.py:2513
msgid "  25 - no such directory"
msgstr "  25 - 没有这种目录"

#: ../satellite_tools/satsync.py:2514
msgid "  26 - mount_point does not exist"
msgstr "  26 - mount_point 不存在"

#: ../satellite_tools/satsync.py:2515
msgid "  27 - No such org"
msgstr "  27 - 没有这种组织"

#: ../satellite_tools/satsync.py:2516
msgid "  28 - error: --master is only valid with --mount-point"
msgstr "  28 - 错误：--master 只在与 --mount-point 结合使用时才有效"

#: ../satellite_tools/satsync.py:2523
#, python-format
msgid "ERROR: unknown dump version, try one of %s"
msgstr "错误：未知转储版本，请尝试使用某个 %s"

#: ../satellite_tools/rhn_satellite_activate.py:198
#, python-format
msgid ""
"\"%s\" (specified in commandline)\n"
"could not be opened and read:\n"
"%s"
msgstr ""
"无法打开和读取（在\n"
"命令行中指定的）\"%s\"\n"
"%s"

#: ../satellite_tools/rhn_satellite_activate.py:205
#, python-format
msgid ""
"\"%s\" could not be opened\n"
"and/or written to:\n"
"%s"
msgstr ""
"无法打开和/或\n"
"写入 \"%s\"：\n"
"%s"

#: ../satellite_tools/reposync.py:121
#, python-format
msgid "%s sync. report from %s"
msgstr "%s 同步报告，来自 %s"

#: ../satellite_tools/messages.py:26
#, python-format
msgid ""
"\n"
"ERROR: executing step %s. Error is:\n"
"%s\n"
msgstr ""
"\n"
"错误：正在执行步骤 %s。错误为：\n"
"%s\n"

#: ../satellite_tools/messages.py:31
#, python-format
msgid ""
"\n"
"ERROR: there was a problem accessing the channel data from your temporary\n"
"       repository. Did you migrate all of the data from the channel ISOs\n"
"       do this directory? If so, please recheck the channels ISOs, ensure\n"
"       that you have them all, and then iteratively remount and repopulate\n"
"       the temporary repository (%s).\n"
msgstr ""
"\n"
"错误：从您的临时储存库访问频道数据时出现\n"
"       问题。您是否已将频道 ISO 中的所有数据\n"
"       迁移到此目录？如果是，请再次检查频道\n"
"       ISO，确保不缺少任何 ISO，然后以交互方式\n"
"       重新装入并重新填充临时储存库 (%s)。\n"

#: ../satellite_tools/messages.py:39
#, python-format
msgid ""
"\n"
"ERROR: there was a problem synchronizing the information.\n"
"       Error message: %s\n"
msgstr ""
"\n"
"错误：同步信息时出现问题。\n"
"       错误消息：%s\n"

#: ../satellite_tools/messages.py:44
#, python-format
msgid ""
"\n"
"ERROR: There was a problem communicating with the ISS Master.\n"
"       Depending on the specific error details, please review your "
"configuration,\n"
"       basic network connectivity, and/or name resolution, and try again.\n"
"       Error message: %s\n"
msgstr ""
"\n"
"错误：与 ISS 主服务器通讯时出现问题。\n"
"       根据具体的错误细节，请检查您的配置、\n"
"       基本网络连接和/或名称解析，然后重试。\n"
"       错误消息：%s\n"

#: ../satellite_tools/messages.py:51
#, python-format
msgid ""
"\n"
"ERROR: a child-channel cannot be synced without its parent being synced as\n"
"       well. A parent needs to be either (a) previously synced or (b) "
"synced\n"
"       in tandem with the desired child-channel. Missing parents for this\n"
"       transaction:\n"
"       %s\n"
msgstr ""
"\n"
"错误：如果不同步子频道的父频道，则无法同步该\n"
"       子频道。父频道需要：(a) 事先已经过同步，\n"
"       或 (b) 配合所需的子频道一起同步。此事务缺少\n"
"       父频道：\n"
"       %s\n"

#: ../satellite_tools/messages.py:59
#, python-format
msgid ""
"\n"
"ERROR: you are not entitled to sync a channel in this set of channels.\n"
"Please contact your SUSE Manager contact\n"
"%s"
msgstr ""
"\n"
"错误：未赋权您同步此频道集中的频道。\n"
"请联系您的 SUSE Manager 联系人\n"
"%s"

#: ../satellite_tools/messages.py:64
#, python-format
msgid "  ERROR: not enough free space (%s KB) on device."
msgstr "  错误：设备上的可用空间不足 (%s KB)。"

#: ../satellite_tools/messages.py:66
#, python-format
msgid "    %3d/%s Fetch successful: %s (%s bytes)"
msgstr "    %3d/%s 提取成功：%s（%s 字节）"

#: ../satellite_tools/messages.py:67
#, python-format
msgid "    Extinct package:  %s"
msgstr "    软件包不存在：%s"

#: ../satellite_tools/messages.py:68
#, python-format
msgid "   Total size: %s"
msgstr "   总大小：%s"

#: ../satellite_tools/messages.py:69
#, python-format
msgid "      Downloaded %s of %s. Estimated remaining time: %s"
msgstr "      已下载 %s，共 %s。估计剩余时间：%s"

#: ../satellite_tools/messages.py:70
#, python-format
msgid "    Fetch unsuccessful: %s"
msgstr "    提取失败：%s"

#: ../satellite_tools/messages.py:71
#, python-format
msgid "   RPM fetch summary: %s"
msgstr "   RPM 提取摘要：%s"

#: ../satellite_tools/messages.py:72
#, python-format
msgid "       success: %d"
msgstr "       成功：%d"

#: ../satellite_tools/messages.py:73
#, python-format
msgid "       failed:  %d"
msgstr "       失败：%d"

#: ../satellite_tools/messages.py:74
#, python-format
msgid "       extinct: %d"
msgstr "       不存在：%d"

#: ../satellite_tools/messages.py:76
#, python-format
msgid "   Retrieving / parsing *relevant* package metadata: %s (%s)"
msgstr "   正在检索/分析 *相关的* 软件包元数据：%s (%s)"

#: ../satellite_tools/messages.py:77
#, python-format
msgid "   Retrieving / parsing errata data: %s (%s)"
msgstr "   正在检索/分析勘误数据：%s (%s)"

#: ../satellite_tools/messages.py:78
#, python-format
msgid "   Retrieving / parsing kickstart data: %s (%s)"
msgstr "   正在检索/分析 kickstart 数据：%s (%s)"

#: ../satellite_tools/messages.py:79
#, python-format
msgid "   Retrieving / parsing kickstart tree files: %s (%s)"
msgstr "   正在检索/分析 kickstart 树文件：%s (%s)"

#: ../satellite_tools/messages.py:80
#, python-format
msgid "   Importing *relevant* package metadata: %s (%s)"
msgstr "   正在导入 *相关的* 软件包元数据：%s (%s)"

#: ../satellite_tools/messages.py:81
msgid "   * WARNING: this may be a slow process."
msgstr "   * 警告：此过程可能需要较长时间。"

#: ../satellite_tools/messages.py:82
msgid "Linking packages to channels"
msgstr "将软件包链接到频道"

#: ../satellite_tools/messages.py:83
#, python-format
msgid "   Importing *relevant* errata: %s (%s)"
msgstr "   正在导入 *相关的* 勘误：%s (%s)"

#: ../satellite_tools/messages.py:84
msgid "   No new kickstartable tree to import"
msgstr "   没有可导入的新 kickstart 树"

#: ../satellite_tools/messages.py:85
#, python-format
msgid "Importing kickstartable trees (%d)"
msgstr "正在导入 kickstart 树 (%d)"

#: ../satellite_tools/messages.py:86
#, python-format
msgid "Imported kickstartable trees (%d)"
msgstr "已导入 kickstart 树 (%d)"

#~ msgid "Crash information is invalid or incomplete"
#~ msgstr "崩溃信息无效或不完整"

#~ msgid "Crash file information is invalid or incomplete"
#~ msgstr "崩溃文件信息无效或不完整"

#~ msgid "Error composing crash directory path"
#~ msgstr "编写崩溃目录路径时出错"

#~ msgid "Error composing crash file path"
#~ msgstr "编写崩溃文件路径时出错"

#~ msgid "Invalid crash name"
#~ msgstr "无效的崩溃名称"

#~ msgid "Crash reporting is disabled for this organization"
#~ msgstr "已为此组织禁用崩溃报告"

#~ msgid "turn off SSL (not recommended)"
#~ msgstr "关闭 SSL（不建议）"

#~ msgid ""
#~ "\n"
#~ "If you have a registration number, please register with it first at "
#~ "http://www.redhat.com/apps/activate/ and then try again.\n"
#~ "\n"
#~ msgstr ""
#~ "\n"
#~ "如果您有注册号，请先在 http://www.redhat.com/apps/activate/ 上使用该注册号"
#~ "注册，然后重试。\n"
#~ "\n"

#~ msgid ""
#~ "\n"
#~ "Invalid Architecture and OS release combination (%s, %s).\n"
#~ "Your system has been registered, but will not receive updates\n"
#~ "because it is not subscribed to a channel. If you have not yet\n"
#~ "activated your product for service, please visit our website at:\n"
#~ "\n"
#~ "     http://www.redhat.com/apps/activate/\n"
#~ "\n"
#~ "...to activate your product."
#~ msgstr ""
#~ "\n"
#~ "体系结构和操作系统发行版的组合无效 (%s, %s)。\n"
#~ "您的系统已注册，但不会接收更新，\n"
#~ "因为它未订阅频道。如果您尚未激活\n"
#~ "服务产品，请访问我们的网站：\n"
#~ "\n"
#~ "     http://www.redhat.com/apps/activate/\n"
#~ "\n"
#~ "...以激活您的产品。"

#~ msgid ""
#~ "\n"
#~ "ERROR: There was a problem communicating with the ISS Master.\n"
#~ "       If the master satellite is older than v5.3, it does not have ISS "
#~ "capability.\n"
#~ "       Otherwise, depending on the specific error details, please review "
#~ "your\n"
#~ "       configuration, basic network connectivity, and/or name resolution, "
#~ "and try again.\n"
#~ "       Error message: %s\n"
#~ msgstr ""
#~ "\n"
#~ "错误：与 ISS 主服务器通讯时出现问题。\n"
#~ "       如果主服务器的从属服务器版本低于 v5.3，则它不具备\n"
#~ "       ISS 功能。否则，请根据具体的错误细节检查您的\n"
#~ "       配置、基本网络连接和/或名称解析，然后重试。\n"
#~ "       错误消息：%s\n"
